### PR TITLE
LPS-149258

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please? Please ignore the SF format issue now, I didn't work on it yet. :)

Thanks
Jeff

**Comment by catarineaguiar** [comment]
@jeffwu0724 

this failure is still happening: https://github.com/jeffwu0724/liferay-portal/pull/101#issuecomment-1170264357

Some failures I found on relevant that I missed before:

`DLFileEntrySearchTest`, `DLFileEntrySearchLegacyDDMIndexFieldsTest`, `DocumentLibraryConvertProcessTest`, 
```
  [exec] com.liferay.document.library.search.test.DLFileEntrySearchTest > testSearchTikaRawMetadata FAILED
     [exec]     java.lang.NoClassDefFoundError: org/apache/poi/ooxml/extractor/ExtractorFactory
     [exec]     	at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:82)
     [exec]     	at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:113)
     [exec]     	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
     [exec]     	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-06/test-1-26/test-portal-acceptance-pullrequest(master)/3767/modules-integration-mysql57-jdk8/0/15/jenkins-console.txt.gz?authuser=0)

`XLSBatchEngineExportTaskItemWriterImplTest`, `XLSBatchEngineImportTaskItemReaderImplTest`
```
 [exec] com.liferay.batch.engine.internal.writer.XLSBatchEngineExportTaskItemWriterImplTest > testWriteRowsWithDefinedFieldNames1 FAILED
     [exec]     java.lang.NoClassDefFoundError: org/apache/commons/io/output/UnsynchronizedByteArrayOutputStream
     [exec]         at com.liferay.batch.engine.internal.writer.XLSBatchEngineExportTaskItemWriterImpl.<init>(XLSBatchEngineExportTaskItemWriterImpl.java:116)
     [exec]         at com.liferay.batch.engine.internal.writer.XLSBatchEngineExportTaskItemWriterImplTest._testWriteRows(XLSBatchEngineExportTaskItemWriterImplTest.java:191)
     [exec]         at com.liferay.batch.engine.internal.writer.XLSBatchEngineExportTaskItemWriterImplTest.testWriteRowsWithDefinedFieldNames1(XLSBatchEngineExportTaskItemWriterImplTest.java:62)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-06/test-1-26/test-portal-acceptance-pullrequest(master)/3767/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

`TextExtractorTest`
```
[exec] com.liferay.portal.tika.test.TextExtractorTest > testDoc FAILED
     [exec]     java.lang.NoSuchFieldError: WORKBOOK_DIR_ENTRY_NAMES
     [exec]     	at org.apache.tika.parser.microsoft.POIFSContainerDetector.detect(POIFSContainerDetector.java:214)
     [exec]     	at org.apache.tika.parser.microsoft.POIFSContainerDetector.detect(POIFSContainerDetector.java:489)
     [exec]     	at org.apache.tika.detect.CompositeDetector.detect(CompositeDetector.java:84)
     [exec]     	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:116)
     [exec]     	at com.liferay.portal.tika.internal.extract.TextExtractorImpl._parseToString(TextExtractorImpl.java:189)
     [exec]     	at com.liferay.portal.tika.internal.extract.TextExtractorImpl.extractText(TextExtractorImpl.java:111)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-06/test-1-26/test-portal-acceptance-pullrequest(master)/3767/modules-integration-mysql57-jdk8/1/4/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
