### PR TITLE
LPS-150836

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi,

This is the fix for LPS-150836, see https://issues.liferay.com/browse/LPS-150836. 
I have checked with Tina and Victor about the solution, and should be good to go.
Please also see https://github.com/jeffwu0724/liferay-portal/pull/46.

Thanks,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:app-servers

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:test:app-servers

**Comment by vicnate5** [comment]
@jeffwu0724 This looks good

**Pull request closed without merging**
