### PR TITLE
LPS-149258

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please? Please ignore the SF format issue now, I didn't work on it yet. :)

Thanks
Jeff

**Comment by catarineaguiar** [comment]
no regressions on relevant.

**Comment by jeffwu0724** [comment]
Hi @catarineaguiar , does ci:test:acceptance also have no error, please? except for the SF issue

**Comment by catarineaguiar** [comment]
@jeffwu0724 testray results of acceptance is not available :(

**Comment by jeffwu0724** [comment]
@catarineaguiar , thanks a lot! Just curious, if the ci is down again, please? seems like many of my test in liferay-portal-ee did not run at all :(

**Comment by catarineaguiar** [comment]
@jeffwu0724 yes, according to this [message](https://liferay.slack.com/archives/C19PWQ74J/p1659632193727839) CI is down

**Comment by catarineaguiar** [comment]
@jeffwu0724 if your changes affect many components, you can run acceptance to check it better.

**Comment by jeffwu0724** [comment]
@catarineaguiar Thanks for letting me know, I will test again when I finish another part :)

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please? Please ignore the SF format issue now, I didn't work on it yet. :)
Also please help me see if this https://github.com/jeffwu0724/liferay-portal/pull/115#issuecomment-1189425646 error also exists.

Thanks
Jeff

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@jeffwu0724 regressions found:

`WikiActivityInterpreterTest`, `WikiPageLocalServiceTest`, `WikiNodeLocalServiceTest`, `MBMessageSearchTest`, 
```
com.liferay.wiki.social.test.WikiActivityInterpreterTest > testActivityInterpreter FAILED
    java.lang.NoClassDefFoundError: org/openxmlformats/schemas/officeDocument/x2006/extendedProperties/CTProperties
    	at org.apache.tika.parser.microsoft.ooxml.MetadataExtractor.extractMetadata(MetadataExtractor.java:127)
    	at org.apache.tika.parser.microsoft.ooxml.MetadataExtractor.extract(MetadataExtractor.java:67)
    	at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:242)
    	at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:113)
    	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:281)
    	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:281)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-27/test-portal-acceptance-pullrequest(master)/4369/modules-integration-mysql57-jdk8/4/0/jenkins-console.txt.gz?authuser=0)

`DDLTest`, `DDLRecordSetServiceTest`, `DDLRecordServiceTest`,
```
 [exec] com.liferay.dynamic.data.lists.util.test.DDLTest > classMethod FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.arquillian.extension.junit.bridge.client.SocketState.writeUTF(SocketState.java:123)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.client.ClientState$1.execute(ClientState.java:127)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.junit.Arquillian.run(Arquillian.java:123)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-27/test-portal-acceptance-pullrequest(master)/4369/modules-integration-mysql57-jdk8/1/13/jenkins-console.txt.gz?authuser=0)

`DDLRecordSearchTest`
```
[exec] com.liferay.dynamic.data.lists.search.test.DDLRecordSearchTest > classMethod FAILED
     [exec]     org.osgi.framework.BundleException: Could not resolve module: com.liferay.dynamic.data.lists.test [1482]
     [exec]       Unresolved requirement: Import-Package: com.github.javaparser
     [exec]         at org.eclipse.osgi.container.Module.start(Module.java:444)
     [exec]         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
     [exec]         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:447)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.connector.FrameworkCommand.lambda$startBundle$37e16ea2$1(FrameworkCommand.java:46)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.connector.ArquillianConnectorThread.run(ArquillianConnectorThread.java:82)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-27/test-portal-acceptance-pullrequest(master)/4369/modules-integration-mysql57-jdk8/1/13/jenkins-console.txt.gz?authuser=0)

`TextExtractorTest`
```
 [exec] com.liferay.portal.tika.test.TextExtractorTest > testDoc FAILED
     [exec]     java.lang.NoClassDefFoundError: org/apache/poi/hwpf/usermodel/Range
     [exec]     	at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:175)
     [exec]     	at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:131)
     [exec]     	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:281)
     [exec]     	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:281)
     [exec]     	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
     [exec]     	at com.liferay.portal.tika.internal.extract.TextExtractorImpl._parseToString(TextExtractorImpl.java:189)
     [exec]     	at com.liferay.portal.tika.internal.extract.TextExtractorImpl.extractText(TextExtractorImpl.java:111)
     [exec]     	at com.liferay.portal.tika.test.TextExtractorTest.extractText(TextExtractorTest.java:214)
     [exec]     	at com.liferay.portal.tika.test.TextExtractorTest.testDoc(TextExtractorTest.java:91)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-27/test-portal-acceptance-pullrequest(master)/4369/modules-integration-mysql57-jdk8/3/6/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
