### PR TITLE
test_jsoup_with_1.10.2

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@jeffwu0724 possible regression:

```
 [exec] com.liferay.fragment.entry.processor.freemarker.test.FragmentEntryProcessorFreemarkerTest > testProcessFragmentEntryLinkHTMLWithConfigurationItemSelectorJournalArticle STARTED
     [exec] 
     [exec] com.liferay.fragment.entry.processor.freemarker.test.FragmentEntryProcessorFreemarkerTest > testProcessFragmentEntryLinkHTMLWithConfigurationItemSelectorJournalArticle FAILED
     [exec]     org.junit.ComparisonFailure: expected:<...language-id="en_US">[<![CDATA[c1]]> 
     [exec]            </dynamic-content> 
     [exec]           </dynamic-element> 
     [exec]          </root></td>
     [exec]         <td>true</td>
     [exec]         <td>false</td>
     [exec]         <td>false</td>
     [exec]         <td>false</td>
     [exec]        </tr>
     [exec]        <tr>
     [exec]         <td>itemSelector1Object.getContentByLocale("es_ES")</td>
     [exec]         <td><!--?xml version="1.0" encoding="UTF-8"?--> <root available-locales="es_ES,en_US" default-locale="en_US" version="1.0">
     [exec]           <dynamic-element field-reference="name" index-type="text" instance-id="yrGixfaX" name="name" type="text">
     [exec]            <dynamic-content language-id="es_ES"><![CDATA[c1-es]]>] 
     [exec]            </dynamic-c...> but was:<...language-id="en_US">[
     [exec]              c1 
     [exec]            </dynamic-content> 
     [exec]           </dynamic-element> 
     [exec]          </root></td>
     [exec]         <td>true</td>
     [exec]         <td>false</td>
     [exec]         <td>false</td>
     [exec]         <td>false</td>
     [exec]        </tr>
     [exec]        <tr>
     [exec]         <td>itemSelector1Object.getContentByLocale("es_ES")</td>
     [exec]         <td><!--?xml version="1.0" encoding="UTF-8"?--> <root available-locales="es_ES,en_US" default-locale="en_US" version="1.0">
     [exec]           <dynamic-element field-reference="name" index-type="text" instance-id="yrGixfaX" name="name" type="text">
     [exec]            <dynamic-content language-id="es_ES">
     [exec]              c1-es] 
     [exec]            </dynamic-c...>
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:117)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
     [exec]     	at com.liferay.fragment.entry.processor.freemarker.test.FragmentEntryProcessorFreemarkerTest.testProcessFragmentEntryLinkHTMLWithConfigurationItemSelectorJournalArticle(FragmentEntryProcessorFreemarkerTest.java:449)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-27/test-portal-acceptance-pullrequest(master)/5306/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
