### PR TITLE
LPS-184385

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @Kvale1733 ,

Could you please help me check this result when you have any free time?
Thanks!

**Comment by Kvale1733** [comment]
@jeffwu0724 Regression found in 2 integration tests

1) com.liferay.portal.util.PortalImplUnitTest
```
 [junit] 
    [junit] Testcase: testGetForwardedHostWithXForwardedHostEnabled(com.liferay.portal.util.PortalImplUnitTest):	Caused an ERROR
    [junit] null
    [junit] java.lang.NullPointerException
    [junit] 	at com.liferay.portal.kernel.util.PrefsPropsUtil.getString(PrefsPropsUtil.java:213)
    [junit] 	at com.liferay.portal.util.PortalImpl.getCDNHostHttps(PortalImpl.java:1809)
    [junit] 	at com.liferay.portal.util.PortalImpl.isValidPortalDomain(PortalImpl.java:6595)
    [junit] 	at com.liferay.portal.util.PortalImpl.isValidPortalDomain(PortalImpl.java:8045)
    [junit] 	at com.liferay.portal.util.PortalImpl.getForwardedHost(PortalImpl.java:2664)
    [junit] 	at com.liferay.portal.util.PortalImplUnitTest.testGetForwardedHostWithXForwardedHostEnabled(PortalImplUnitTest.java:224)
    [junit] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-40/test-portal-acceptance-pullrequest(master)/2628/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

2) com.liferay.portal.util.PortalImplEscapeRedirectTest
```
 [junit] Testcase: testEscapeRedirectWithSubdomains(com.liferay.portal.util.PortalImplEscapeRedirectTest):	Caused an ERROR
    [junit] null
    [junit] java.lang.NullPointerException
    [junit] 	at com.liferay.portal.kernel.util.PrefsPropsUtil.getString(PrefsPropsUtil.java:213)
    [junit] 	at com.liferay.portal.util.PortalImpl.getCDNHostHttps(PortalImpl.java:1809)
    [junit] 	at com.liferay.portal.util.PortalImpl.isValidPortalDomain(PortalImpl.java:6595)
    [junit] 	at com.liferay.portal.util.PortalImpl.isValidPortalDomain(PortalImpl.java:8045)
    [junit] 	at com.liferay.portal.util.PortalImpl.escapeRedirect(PortalImpl.java:926)
    [junit] 	at com.liferay.portal.util.PortalImplEscapeRedirectTest.testEscapeRedirectWithSubdomains(PortalImplEscapeRedirectTest.java:252)
    [junit] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    [junit] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-40/test-portal-acceptance-pullrequest(master)/2628/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)


Also there is an sf issues. Seems SF wants each host listed row by row

**Comment by jeffwu0724** [comment]
Thanks! @Kvale1733

**Comment by jeffwu0724** [comment]
ci:test:sf

**Pull request closed without merging**
