### PR TITLE
Remove deprecated for portal kernel part ten

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is remove_deprecated_for_portal_kernel_part_Ten.
Thanks for checking. Also see https://github.com/jeffwu0724/liferay-portal/pull/61

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
@catarineaguiar Please help me scan test results.

Thanks
Jeff

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Pull request closed without merging**
