### PR TITLE
remove_usage_of_stream_on_object_rest_impl

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @Kvale1733, could you please help me check the result, please?
Thanks!

**Comment by Kvale1733** [comment]
@jeffwu0724 Regressions found

1) Several com.liferay.object.rest.internal.resource.v1_0.test tests are failing with similar errors such as

com.liferay.object.rest.internal.resource.v1_0.test.SystemObjectRelatedObjectsTest
```
 [exec] com.liferay.object.rest.internal.resource.v1_0.test.SystemObjectRelatedObjectsTest > testGetManyToManySystemObjectRelatedObjects STARTED
[beanshell] 2022-12-22 01:19:14.192 WARN  [com.liferay.object.rest.test-executor-thread][FinderCacheImpl:342] Unable to find corresponding model impl class for table R_20098AxOeKIEsR_User_atnj
[beanshell] 2022-12-22 01:19:19.717 WARN  [http-nio-8080-exec-4][FinderCacheImpl:342] Unable to find corresponding model impl class for table R_20098AxOeKIEsR_User_atnj
[beanshell] 2022-12-22 01:19:19.720 ERROR [http-nio-8080-exec-4][EntityExtensionWriterInterceptor:74] null
[beanshell] java.lang.RuntimeException: java.lang.NullPointerException
```

```
 [exec] com.liferay.object.rest.internal.resource.v1_0.test.SystemObjectRelatedObjectsTest > testGetManyToManySystemObjectRelatedObjects FAILED
     [exec]     java.lang.AssertionError: Thread Thread[http-nio-8080-exec-4,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.vulcan.internal.jaxrs.exception.mapper.ExceptionMapper, message=null
     [exec]     java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.vulcan.internal.jaxrs.exception.mapper.ExceptionMapper, message=null
     [exec]     	at com.liferay.portal.test.rule.LogAssertionTestRule$LogAppender.append(LogAssertionTestRule.java:330)
```
[Log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-30/test-portal-acceptance-pullrequest(master)/5894/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Pull request closed without merging**
