### PR TITLE
LPS-144860

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar , could you please help me check what goes wrong here?

**Comment by catarineaguiar** [comment]
@jeffwu0724 most tests failed on startup due to:

```
    [junit] 2023-01-27 02:28:27.615 DEBUG [Start Level: Equinox Container: 5e1d27dd-ea14-4901-84bc-ee5a54d4a6e3][BundleStartStopLogger:86] STARTED com.liferay.learn.taglib_3.0.1 [1458]
    [junit] 2023-01-27 02:28:27.827 ERROR [main][DirectoryWatcher:1173] Unable to start bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.shared.dependencies.jasperreports.jar
    [junit] org.osgi.framework.BundleException: Could not resolve module: com.liferay.shared.dependencies.jasperreports [921]
    [junit]   Unresolved requirement: Import-Package: antlr
    [junit] 
    [junit] 	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
    [junit] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428) ~[org.eclipse.osgi.jar:?]
    [junit] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundle(DirectoryWatcher.java:1156) [bundleFile:?]
    [junit] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundles(DirectoryWatcher.java:1189) [bundleFile:?]
    [junit] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startAllBundles(DirectoryWatcher.java:1130) [bundleFile:?]
    [junit] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:1041) [bundleFile:?]
    [junit] 	at com.liferay.portal.file.install.internal.DirectoryWatcher.start(DirectoryWatcher.java:290) [bundleFile:?]
    [junit] 	at com.liferay.portal.file.install.internal.activator.FileInstallImplBundleActivator.start(FileInstallImplBundleActivator.java:107) [bundleFile:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-26/test-portal-acceptance-pullrequest(master)/7269/functional-smoke-tomcat90-mysql57-jdk11_open/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
@catarineaguiar 
Could you please help me to check if there is any new regression when you have time, please?
Thanks!

**Comment by jeffwu0724** [comment]
@catarineaguiar
Could you please help me to check if there is any new regression when you have time, please?
Thanks!

**Comment by jeffwu0724** [comment]
Hey @Kvale1733, could you please help me check what is the regression when you have any free time, please?

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 Regressions found

1)com.liferay.portal.reports.engine.console.jasper.internal.test.ReportEngineImplTest
```
[exec] com.liferay.portal.reports.engine.console.jasper.internal.test.ReportEngineImplTest > testCompileCsv FAILED
     [exec]     java.lang.NoClassDefFoundError: org/eclipse/jdt/internal/compiler/env/INameEnvironment
     [exec]     	at net.sf.jasperreports.engine.JasperCompileManager.getJavaCompiler(JasperCompileManager.java:739)
     [exec]     	at net.sf.jasperreports.engine.JasperCompileManager.getCompiler(JasperCompileManager.java:856)
     [exec]     	at net.sf.jasperreports.engine.JasperCompileManager.compile(JasperCompileManager.java:358)
     [exec]     	at net.sf.jasperreports.engine.JasperCompileManager.compile(JasperCompileManager.java:344)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-02/test-1-37/test-portal-acceptance-pullrequest(master)/8871/modules-integration-mysql57-jdk8/4/8/jenkins-console.txt.gz?authuser=0)

2) Cannot view report (seems related)

Steps to reproduce:
        1. Go to Configuration > Reports Admin in the product menu
        2. Go to Definitions tab
        3. Create a new definition using this Report Template: https://drive.google.com/file/d/1caWA6qetyjlc9UG_bag0jczMMa8TD_GS/view?usp=sharing
        4. Click on created definition entry
        5. Click Add Report
        6. Click generate report 
        7. Click on created report entry
        
 Expected Results: Can view report (

Before

Actual Results: Processing report, this may take several minutes message appears and report is not shown.
after1
appears under attachements)

**Pull request closed without merging**
