### PR TITLE
LPS-155991

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
@jeffwu0724 regression found:

`DLOpenerGoogleDriveManagerTest`
```
com.liferay.document.library.opener.google.drive.test.DLOpenerGoogleDriveManagerTest > classMethod FAILED
    org.osgi.framework.BundleException: Could not resolve module: com.liferay.document.library.opener.google.drive.test [1437]
      Unresolved requirement: Import-Package: com.liferay.portal.configuration.test.util
        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:447)
        at com.liferay.arquillian.extension.junit.bridge.connector.FrameworkCommand.lambda$startBundle$37e16ea2$1(FrameworkCommand.java:46)
        at com.liferay.arquillian.extension.junit.bridge.connector.ArquillianConnectorThread.run(ArquillianConnectorThread.java:82)
```
```
[exec] com.liferay.document.library.opener.google.drive.test.DLOpenerGoogleDriveManagerTest > testCheckInUploadsAnEmptyFileToGoogle FAILED
     [exec]     java.lang.NoClassDefFoundError: io/opencensus/trace/propagation/TextFormat$Setter
     [exec]     	at com.google.api.client.http.HttpRequest.<init>(HttpRequest.java:203)
     [exec]     	at com.google.api.client.http.HttpTransport.buildRequest(HttpTransport.java:115)
     [exec]     	at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:86)
     [exec]     	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:300)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-07/test-1-32/test-portal-acceptance-pullrequest(master)/4924/modules-integration-mysql57-jdk8/1/5/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
@jeffwu0724 this [regression](https://github.com/jeffwu0724/liferay-portal/pull/119#issuecomment-1195872144) keep happening

**Comment by catarineaguiar** [comment]
no other regression was found.

**Pull request closed without merging**
