### PR TITLE
LPS-149258

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
@jeffwu0724 regressions found:

`WikiPageLocalServiceTest`, `WikiActivityInterpreterTest`, `WikiPageStagedModelDataHandlerTest`, `WikiPageSearchTest`, `MBMessageSearchTest`, `DLFileEntrySearchLegacyDDMIndexFieldsTest`,  `DocumentLibraryConvertProcessTest`
```
     [exec] com.liferay.wiki.service.test.WikiPageLocalServiceTest > testCopyPage STARTED
[beanshell] 2022-09-17 01:53:34.386 WARN  [com.liferay.wiki.test-executor-thread][SAXHelper:128] SAX Security Manager could not be setup [log suppressed for 5 minutes]
[beanshell] org.xml.sax.SAXNotRecognizedException: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
[beanshell] 	at org.apache.xerces.parsers.AbstractSAXParser.getProperty(Unknown Source) ~[xercesImpl.jar:?]
[beanshell] 	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.setProperty(Unknown Source) ~[xercesImpl.jar:?]
[beanshell] 	at org.apache.xmlbeans.impl.common.SAXHelper.trySetXercesSecurityManager(SAXHelper.java:124) ~[?:?]
[beanshell] 	at org.apache.xmlbeans.impl.common.SAXHelper.newXMLReader(SAXHelper.java:50) ~[?:?]
[beanshell] 	at org.apache.xmlbeans.impl.store.Locale.getSaxLoader(Locale.java:2227) ~[?:?]
[beanshell] 	at org.apache.xmlbeans.impl.store.Locale.lambda$parseToXmlObject$3(Locale.java:715) ~[?:?]
[beanshell] 	at org.apache.xmlbeans.impl.store.Locale.syncWrap(Locale.java:488) ~[?:?]
[beanshell] 	at org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:714) ~[?:?]
```
```
 [exec] com.liferay.wiki.service.test.WikiPageLocalServiceTest > testCopyPage FAILED
     [exec]     java.lang.LinkageError: org/apache/xmlbeans/XmlCursor
     [exec]     	at org.apache.tika.parser.microsoft.ooxml.XWPFWordExtractorDecorator.extractParagraph(XWPFWordExtractorDecorator.java:229)
     [exec]     	at org.apache.tika.parser.microsoft.ooxml.XWPFWordExtractorDecorator.extractIBodyText(XWPFWordExtractorDecorator.java:161)
     [exec]     	at org.apache.tika.parser.microsoft.ooxml.XWPFWordExtractorDecorator.buildXHTML(XWPFWordExtractorDecorator.java:124)
     [exec]     	at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.getXHTML(AbstractOOXMLExtractor.java:137)
     [exec]     	at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:245)
     [exec]     	at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:113)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-25/test-portal-acceptance-pullrequest(master)/4640/modules-integration-mysql57-jdk8/4/1/jenkins-console.txt.gz?authuser=0)

`TextExtractorTest`
```
 [exec] com.liferay.portal.tika.test.TextExtractorTest > testDocx FAILED
     [exec]     java.lang.LinkageError: loader constraint violation: loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) previously initiated loading for a different type with name "org/apache/xmlbeans/XmlCursor"
     [exec]     	at java.lang.ClassLoader.defineClass1(Native Method)
     [exec]     	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
     [exec]     	at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:276)
     [exec]     	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:634)
     [exec]     	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:555)
     [exec]     	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:514)
     [exec]     	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:501)
     [exec]     	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:324)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-25/test-portal-acceptance-pullrequest(master)/4640/modules-integration-mysql57-jdk8/3/7/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
Hi @jeffwu0724 I found a possible regression in some functional tests:

**Steps to reproduce:**

1. Go to Configuration > Reports Admin
2. In Definitions tab > Create a new definition
3. Give it a name and choose a file > save
4. Edit the new definition > Add report > generate

Expected result:
A new report can be generated without errors

Actual result:
When a report is generated a failure is shown in the logs and when you go to the report created an alert appears `An error occurred while processing the report.`

```
2022-09-21 14:45:04.646 ERROR [liferay/reports_admin-2][SerialDestination:64] Unable to process message {destinationName=liferay/reports_admin, response=null, responseDestinationName=null, responseId=43106, payload=com.liferay.portal.reports.engine.ByteArrayReportResultContainer@16bff960, values={defaultLocale=en_US, companyId=20097, groupId=0, principalName=20125, permissionChecker=com.liferay.portal.kernel.util.TransientValue@7614100, siteDefaultLocale=en_US, themeDisplayLocale=en_US}}
com.liferay.portal.kernel.messaging.MessageListenerException: com.liferay.portal.reports.engine.console.exception.NoSuchEntryException: No Entry exists with the primary key 43106
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:41) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74) ~[portal-kernel.jar:?]
	at com.liferay.portal.messaging.internal.SerialDestination$1.run(SerialDestination.java:59) [bundleFile:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
```

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar , could you please help me check the result again when it is ready, please? Seems like I cannot reproduce this bug after some small update.

Thanks!

**Comment by catarineaguiar** [comment]
@jeffwu0724 the functional tests failed again, you can see more information of the failure [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-38/test-portal-acceptance-pullrequest(master)/3830/functional-tomcat90-mysql57-jdk8/1/22/jenkins-console.txt.gz?authuser=0)

```
  [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.CPReportsadmin#DownloadReportXLS] STANDARD_ERROR
     [exec]     org.dom4j.DocumentException: Error on line 9161 of document  : An invalid XML character (Unicode: 0x5) was found in the CDATA section. Nested exception: An invalid XML character (Unicode: 0x5) was found in the CDATA section.
     [exec]     	at org.dom4j.io.SAXReader.read(SAXReader.java:482)
     [exec]     	at org.dom4j.io.SAXReader.read(SAXReader.java:343)
     [exec]     	at com.liferay.poshi.runner.selenium.LiferaySeleniumUtil.assertConsoleErrors(LiferaySeleniumUtil.java:103)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.assertLiferayErrors(BaseWebDriverImpl.java:492)
     [exec]     	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.poshi.runner.PoshiRunnerExecutor$1.call(PoshiRunnerExecutor.java:1179)
     [exec]     	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
     [exec]     Nested exception: 
     [exec]     org.xml.sax.SAXParseException; lineNumber: 9161; columnNumber: 38; An invalid XML character (Unicode: 0x5) was found in the CDATA section.
     [exec]     	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
     [exec]     	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
     [exec]     	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
     [exec]     	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
     [exec]     	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
     [exec]     	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
```

**Comment by jeffwu0724** [comment]
@catarineaguiar , hmmm, okk, thanks!

**Comment by catarineaguiar** [comment]
@jeffwu0724 when you follow the steps I sent [here](https://github.com/jeffwu0724/liferay-portal/pull/143#issuecomment-1253821176) the failure doesn't happen?

**Comment by jeffwu0724** [comment]
@catarineaguiar , yea, after I made changes[ here](https://github.com/jeffwu0724/liferay-portal/pull/143/commits/a4e29f175cabba39df14c30c48633fa6dae73e59), the bugs you found above about generating report cannot be reproduced at my end

**Comment by jeffwu0724** [comment]
@catarineaguiar I will try to build again and see if I can reproduce it this time

**Comment by catarineaguiar** [comment]
@jeffwu0724 I can reproduce too :/

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @Kvale1733 , could you please help me to check the result when you have time?

Thanks!
Jeff

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@zhangyan0701  

Can you help check the results when they are out? Thanks.

**Comment by zhangyan0701** [comment]
1. Some ReportAdmin tests failed.
Steps:
- Go to Site Admin > Configuration > Reports Admin.
- Go to Definitions tab and add a new definition.
- Upload template file https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/portal-reports-engine-console/portal-reports-engine-console-test/src/testFunctional/tests/dependencies/reports_admin_template_source_sample_class_name.jrxml.
- In the definition, add a new report, click Generate, assert warning `DocumentSummaryInformation property set came back as null` in console.
- Go to Reports tab and click into the new report.
- Error occurs: "Error on line 8912 of document  : An invalid XML character (Unicode: 0x5) was found in the CDATA section. Nested exception: An invalid XML character (Unicode: 0x5) was found in the CDATA section."

Testray: https://testray.liferay.com/home/-/testray/case_results/1993458493

2. Some integration tests seem related:
[com.liferay.portal.tika.test.TextExtractorTest](https://testray.liferay.com/home/-/testray/case_results/1993460805): NullPointerException
[com.liferay.document.library.search.test.DLFileEntrySearchTest](https://testray.liferay.com/home/-/testray/case_results/1993460241): AssertionError
[com.liferay.document.library.search.test.DLFileEntrySearchLegacyDDMIndexFieldsTest](https://testray.liferay.com/home/-/testray/case_results/1993460224): AssertionError

**Pull request closed without merging**
