### PR TITLE
test_remove_xmpcore

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
Hey @Kvale1733, could you please help me check the test result when it is ready, please?
Thanks!

**Comment by Kvale1733** [comment]
@jeffwu0724 Failure on startup with reports component

```
[beanshell] 2022-11-30 01:33:59.836 ERROR [main][DirectoryWatcher:1176] Unable to start bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/portal/com.liferay.portal.reports.engine.console.jasper.jar
[beanshell] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.reports.engine.console.jasper [221]
[beanshell]   Unresolved requirement: Import-Package: com.microsoft.schemas.office.powerpoint; resolution:="optional"
[beanshell]   Unresolved requirement: Import-Package: com.microsoft.schemas.office.word; resolution:="optional"
[beanshell]   Unresolved requirement: Import-Package: net.sf.cglib.proxy; resolution:="optional"
[beanshell]   Unresolved requirement: Import-Package: org.apache.batik.anim.dom; resolution:="optional"
[beanshell]   Unresolved requirement: Import-Package: org.apache.batik.bridge; resolution:="optional"
[beanshell]   Unresolved requirement: Import-Package: org.apache.batik.dom; resolution:="optional"
```

[Log](https://testray.liferay.com/reports/production/logs/2022-11/test-1-30/test-portal-acceptance-pullrequest(master)/5559/functional-tomcat90-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
