### PR TITLE
LPS-183594

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @zhangyan0701  ,

Could you please help me check what is wrong here?
Thanks!

**Comment by jeffwu0724** [comment]
Hey @Kvale1733  ,

Could you please help me check what is wrong here?
Thanks!

**Comment by Kvale1733** [comment]
@jeffwu0724 All tests failed due to a startup issue. 

```
[beanshell] 2023-06-15 03:01:18.980 INFO  [main][ModuleFrameworkImpl:281] Navigate to Control Panel > System > Gogo Shell and enter "lb" to see all bundles
[beanshell] 2023-06-15 03:01:21.593 ERROR [SystemExecutorServiceUtil-3][ROOT:56] bundle com.liferay.document.library.taglib:4.0.4 (1455)[com.liferay.document.library.taglib.internal.servlet.RepositoryBrowserServlet(11645)] : Field _dlAppService cannot be found in component class com.liferay.document.library.taglib.internal.servlet.RepositoryBrowserServlet. The field will be ignored.
[beanshell] java.lang.NoClassDefFoundError: Lcom/liferay/portal/upload/UploadPortal;
[beanshell] 	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_121]
[beanshell] 	at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_121]
[beanshell] 	at java.lang.Class.getDeclaredField(Class.java:2068) ~[?:1.8.0_121]
[beanshell] 	at org.apache.felix.scr.impl.inject.field.FieldUtils.getField(FieldUtils.java:154) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.inject.field.FieldUtils.searchField(FieldUtils.java:87) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.inject.field.FieldHandler$NotResolved.resolve(FieldHandler.java:360) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.inject.field.FieldHandler$NotResolved.fieldExists(FieldHandler.java:378) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.inject.field.FieldHandler.fieldExists(FieldHandler.java:434) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.inject.field.FieldHandler$ReferenceMethodImpl.getServiceObject(FieldHandler.java:515) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2308) ~[?:?]
```
[Log](https://testray.liferay.com/reports/production/logs/2023-06/test-1-39/test-portal-acceptance-pullrequest(master)/5371/functional-smoke-tomcat90-postgresql144-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
