### PR TITLE
Test configuration for upload

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hi @zhangyan0701 ,

could you please help me check the test result when you have any free time, please?
Thanks!

**Comment by catarineaguiar** [comment]
ci:test:bundle

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
ci:stop:bundle

**Comment by catarineaguiar** [comment]
@jeffwu0724 sorry the delay. Regression found:

Steps to reproduce:

1. go to Content & data > Documents and media > add a new document and media
2. select a document and publish

Actual result:
the document is not published and an error is shown in the logs
```
2023-06-06 23:03:19.129 ERROR [http-nio-8080-exec-9][ServiceProxyFactory:278] Service "com.liferay.document.library.kernel.store.Store{(default=true)}" is unavailable in 60000 milliseconds while setting field "_store" for class "com.liferay.portlet.documentlibrary.store.DLStoreImpl", will retry...
```
Expected result:
The document is published without errors

**Comment by jeffwu0724** [comment]
@catarineaguiar 
Thanks a lot for checking!

**Comment by jeffwu0724** [comment]
ci:test:bundle

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hi @catarineaguiar ,

could you please help me check the test result when you have any free time, please?
(Please ignore the SF for now)
Thanks!

**Comment by Kvale1733** [comment]
@jeffwu0724 Regression found. Cannot add attachment to Message Board Thread

Steps to reproduce:
1. Go to Content & Data > Message Boards
2. Click the blue plus button 
3. Select Thread 
4. Click attachment panel to open it

Expected Results: There is a Select File button to select a file for attachment
Actual Results: There is no Select File button

https://github.com/jeffwu0724/liferay-portal/assets/90647688/14df5c3a-50eb-4b50-a8cf-63515a3def52

**Pull request closed without merging**
