### PR TITLE
update_xmlbeans_new

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
tried to fixed the bugs in https://github.com/jeffwu0724/liferay-portal/pull/147#issuecomment-1256123677

**Comment by jeffwu0724** [comment]
@Kvale1733 can you check the results when it finishes, please? Thanks!

**Comment by Kvale1733** [comment]
@jeffwu0724 All tests failed to run on CI. In the logs all have:

`2: Task failed with an exception.
     [exec] -----------
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:commerce:commerce-product-service:jar'.
     [exec] > Bundle com.liferay.commerce.product.service-6.0.80.jar has errors
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:commerce-product-service:jar'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$3(ExecuteActionsTaskExecuter.java:186)
     [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:268)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)
     [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)` [Example log](https://testray.liferay.com/reports/production/logs/2022-09/test-1-30/test-portal-acceptance-pullrequest(master)/4739/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
