### PR TITLE
LPS-147085

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for https://issues.liferay.com/browse/LPS-147085.
Can also see https://github.com/jeffwu0724/liferay-portal/pull/60.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
@catarineaguiar  Can you help me look at the test result, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Pull request closed without merging**
