### PR TITLE
Remove deprecated part 6

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi, 

I remove deprecated for 
"portal-impl/src/com/liferay/portlet/documentlibrary/service/impl" - DLApp
"portal-impl/src/com/liferay/portlet/documentlibrary/service/impl" - DLFolder
"portal-impl/src/com/liferay/portlet/documentlibrary/service/impl" - DLFileEntry
"portal-impl/src/com/liferay/portlet/documentlibrary/service/permission"
"portal-impl/src/com/liferay/portlet/documentlibrary/store"
"portal-impl/src/com/liferay/portlet/documentlibrary/util"
"portal-impl/src/com/liferay/portlet/social/service/impl/SocialActivityLocalServiceImpl.java"
Thanks for checking. Also see https://github.com/jeffwu0724/liferay-portal/pull/32

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by kyle-miho** [comment]
@jeffwu0724 failures are unrelated

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result again, please?

Thanks
Jeff

**Comment by kyle-miho** [comment]
@jeffwu0724 failures unrelated

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:stable

**Comment by jeffwu0724** [comment]
ci:test

**Comment by kyle-miho** [comment]
@jeffwu0724 failures should be unrelated

**Pull request closed without merging**
