### PR TITLE
LPS-182384

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hi @zhangyan0701 
could you please help me check the test result when you have any free time?
Thanks!

**Comment by zhangyan0701** [comment]
@jeffwu0724

The failure in test [com.liferay.portal.upload.internal.LiferayFileItemTest](https://testray.liferay.com/home/-/testray/case_results/2283768089) seems related:
`testGetContentTypeFromRealFile: java.lang.NullPointerException`

Full console:
https://testray.liferay.com/reports/production/logs/2023-04/test-1-32/test-portal-acceptance-pullrequest(master)/9295/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0

Other failure should be unrelated.

**Comment by jeffwu0724** [comment]
Thanks @zhangyan0701 ! 

Have fixed and force pushed the code, and that failure in the test should have gone

**Comment by zhangyan0701** [comment]
ci:test:relevant:norebase

**Comment by zhangyan0701** [comment]
Hi @jeffwu0724 

The test passed in the new relevant test.

**Comment by jeffwu0724** [comment]
@zhangyan0701 
Thanks for checking!

**Pull request closed without merging**
