### PR TITLE
LPS-157036

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang, 

This is for ticket https://issues.liferay.com/browse/LPS-157036.
Thanks for checking.

for reference https://github.com/shuyangzhou/liferay-portal/pull/9537/commits
https://github.com/brianchandotcom/liferay-portal/pull/68979/commits

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
Testray results didn't display :(
I'm going to run it again

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@jeffwu0724 I don't know what is happening with testray results, maybe you need to resend.

**Pull request closed without merging**
