### PR TITLE
LPS-145171 - Make changes to "wsadmin.py", "build.xml", and relocate …

### PR DESCRIPTION
**Pull request by jeffwu0724**
…unused properties

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@vicnate5 Hi Victor,

I removed some codes about "wsadmin" in build.xml. and also made some related changes.
These changes did not pass the ci test, and would you mind helping me check with it, please?

Thanks,
Jeff

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
The tests did not run, re-trying

**Comment by vicnate5** [comment]
Actually, given the type of changes, I do not think it is worth running the full default suite on this, we can focus on Websphere

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
@jeffwu0724 Websphere fails on CI

```
update-app-server-scripts:
     [exec] ADMU0116I: Tool information is being logged in file
     [exec]            /opt/dev/projects/github/liferay-portal/bundles/websphere-9.0.0.0/profiles/liferay/logs/server1/startServer.log
     [exec] ADMU0128I: Starting tool with the liferay profile
     [exec] ADMU3100I: Reading configuration for server: server1
     [exec] ADMU3028I: Conflict detected on port 2809.  Likely causes: a) An instance of
     [exec]            the server server1 is already running  b) some other process is
     [exec]            using port 2809
     [exec] ADMU3029I: Conflict detected on port 2809 for endpoint
     [exec]            JSR160RMI_CONNECTOR_ADDRESS of the server server1 
     [exec] ADMU3027E: An instance of the server may already be running: server1
     [exec] ADMU0111E: Program exiting with error:
     [exec]            com.ibm.websphere.management.exception.AdminException: ADMU3027E: An
     [exec]            instance of the server may already be running: server1
     [exec] ADMU1211I: To obtain a full trace of the failure, use the -trace option.
     [exec] ADMU0211I: Error details may be seen in the file:
     [exec]            /opt/dev/projects/github/liferay-portal/bundles/websphere-9.0.0.0/profiles/liferay/logs/server1/startServer.log
     [exec] Result: 255
     [echo] Installing liferay-portal.war.
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:5328: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1657: Task [run-batch-test] failed after [1] attempts; giving up.
     [echo] Error messages:
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1788: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1152: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:11155: Warning: Could not find file /opt/dev/projects/github/liferay-portal/bundles/websphere-9.0.0.0/profiles/liferay/installedApps/liferay-cell/liferay-portal.ear/liferay-portal.war/WEB-INF/ibm-web-ext.xml to copy.
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1788: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1152: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:11155: Warning: Could not find file /opt/dev/projects/github/liferay-portal/bundles/websphere-9.0.0.0/profiles/liferay/installedApps/liferay-cell/liferay-portal.ear/liferay-portal.war/WEB-INF/ibm-web-ext.xml to copy.
```

**Comment by jeffwu0724** [comment]
> @jeffwu0724 Websphere fails on CI
> 
> ```
> update-app-server-scripts:
>      [exec] ADMU0116I: Tool information is being logged in file
>      [exec]            /opt/dev/projects/github/liferay-portal/bundles/websphere-9.0.0.0/profiles/liferay/logs/server1/startServer.log
>      [exec] ADMU0128I: Starting tool with the liferay profile
>      [exec] ADMU3100I: Reading configuration for server: server1
>      [exec] ADMU3028I: Conflict detected on port 2809.  Likely causes: a) An instance of
>      [exec]            the server server1 is already running  b) some other process is
>      [exec]            using port 2809
>      [exec] ADMU3029I: Conflict detected on port 2809 for endpoint
>      [exec]            JSR160RMI_CONNECTOR_ADDRESS of the server server1 
>      [exec] ADMU3027E: An instance of the server may already be running: server1
>      [exec] ADMU0111E: Program exiting with error:
>      [exec]            com.ibm.websphere.management.exception.AdminException: ADMU3027E: An
>      [exec]            instance of the server may already be running: server1
>      [exec] ADMU1211I: To obtain a full trace of the failure, use the -trace option.
>      [exec] ADMU0211I: Error details may be seen in the file:
>      [exec]            /opt/dev/projects/github/liferay-portal/bundles/websphere-9.0.0.0/profiles/liferay/logs/server1/startServer.log
>      [exec] Result: 255
>      [echo] Installing liferay-portal.war.
>      [echo] The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:5328: The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1657: Task [run-batch-test] failed after [1] attempts; giving up.
>      [echo] Error messages:
>      [echo] The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1788: The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1152: The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:11155: Warning: Could not find file /opt/dev/projects/github/liferay-portal/bundles/websphere-9.0.0.0/profiles/liferay/installedApps/liferay-cell/liferay-portal.ear/liferay-portal.war/WEB-INF/ibm-web-ext.xml to copy.
>      [echo] The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1788: The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1152: The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:11155: Warning: Could not find file /opt/dev/projects/github/liferay-portal/bundles/websphere-9.0.0.0/profiles/liferay/installedApps/liferay-cell/liferay-portal.ear/liferay-portal.war/WEB-INF/ibm-web-ext.xml to copy.
> ```

Thanks Victor, so it means I should not remove these code in build.xml, please?

**Comment by vicnate5** [comment]
@jeffwu0724 Go ahead and remove what is needed.

**Pull request closed without merging**
