### PR TITLE
LPS-150836

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi,

This is the fix for LPS-150836, see https://issues.liferay.com/browse/LPS-150836.
I have checked with Tina and Victor about the solution, and should be good to go.
Please also see https://github.com/jeffwu0724/liferay-portal/pull/46.

Thanks,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
Hey @vicnate5 , I have talked with Tina, and we made some other changes, and would you mind helping me check with the result again, please?
Thanks,
Jeff

**Comment by vicnate5** [comment]
Will check this Monday morning.

**Comment by jeffwu0724** [comment]
ci:test:app-servers

**Comment by brianchandotcom** [comment]
@jeffwu0724 thanks. I merged this manually.

**Comment by vicnate5** [comment]
@jeffwu0724 No issues found in test results.

**Pull request closed without merging**
