### PR TITLE
LPS-171249 upgrade Netty/Codec/HTTP in shared-dependencies-netty

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang, 

This is for ticket https://issues.liferay.com/browse/LPS-171249.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar , could you please help me check if this [regression](https://github.com/liferay-core-infra/liferay-portal/pull/2789#issuecomment-1359712459) found here, please? I tried to reproduce locally, but seems like I cannot see that regression.
Thanks!

**Comment by catarineaguiar** [comment]
@jeffwu0724 the test passed on relevant and locally for me :)

**Pull request closed without merging**
