### PR TITLE
LPS-149258

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

As we talked, I have
1. Move poi related stuff out to separate module with version 5.2.2, use lite rather than full
2. Upgrade tika to 1.28.5

In order to show error about xmlbeans, and jasperreport, I didn't make any change to them. Also, in my shared-dependencies-poi, I didn't add all the needed dependencies as I did [here](https://github.com/jeffwu0724/liferay-portal/pull/143/commits/e17362e01e9bf615ae8e03d1fc029c2e2555093c) yet.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
@Kvale1733 Can you help me look at the test result when it is ready, please?

Thanks
Jeff

**Comment by Kvale1733** [comment]
@zhangyan0701 Can you please help with this I"m getting off and the results still aren't uploaded to testray. Thanks.

**Comment by zhangyan0701** [comment]
No regressions found in the relevant tests.

But the SF issues 3 and 4 should be related:
```
     [java] 3: ./modules/apps/portal/portal-tika/build.gradle expected:<...n: "1.28.5"
     [java] 	compile[Include group: "org.ccil.cowan.tagsoup", name: "tagsoup", version: "1.2.1"
     [java] 	compileInclude group: "org.gagravarr", name: "vorbis-java-core", version: "0.8"
     [java] 	compileInclude group: "org.tallison", name: "jmatio", version: "1.2"
     [java] 
     [java] 	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
     [java] 	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
     [java] 	compileOnly group: "com.zaxxer", name: "SparseBitSet", version: "1.2"
     [java] 	compileOnly group: "org.apache.commons", name: "commons-math3", version: "3.6.1"
     [java] 	compileOnly group: "org.apache.poi", name: "poi", version: "5.2.2"
     [java] 	compileOnly group: "org.apache.poi", name: "poi-ooxml", version: "5.2.2"
     [java] 	compileOnly group: "org.apache.poi", name: "poi-ooxml-lite", version: "5.2.2"
     [java] 	compileOnly group: "org.apache.xmlbeans", name: "xmlbeans", version: "5.0.3]"
     [java] 	compileOnly group...> but was:<...n: "1.28.5"
     [java] 	compile[Only group: "org.apache.xmlbeans", name: "xmlbeans", version: "5.0.3"
     [java] 	compileInclude group: "org.ccil.cowan.tagsoup", name: "tagsoup", version: "1.2.1"
     [java] 	compileInclude group: "org.gagravarr", name: "vorbis-java-core", version: "0.8"
     [java] 	compileInclude group: "org.tallison", name: "jmatio", version: "1.2"
     [java] 
     [java] 	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
     [java] 	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
     [java] 	compileOnly group: "com.zaxxer", name: "SparseBitSet", version: "1.2"
     [java] 	compileOnly group: "org.apache.commons", name: "commons-math3", version: "3.6.1"
     [java] 	compileOnly group: "org.apache.poi", name: "poi", version: "5.2.2"
     [java] 	compileOnly group: "org.apache.poi", name: "poi-ooxml", version: "5.2.2"
     [java] 	compileOnly group: "org.apache.poi", name: "poi-ooxml-lite", version: "5.2.2]"
     [java] 	compileOnly group...>
     [java] 4: ./modules/apps/application-list/application-list-taglib/src/main/resources/META-INF/resources/panel/page.jsp expected:<...t(
     [java] 			"categoryKey",[ ]panelCategory.getKey...> but was:<...t(
     [java] 			"categoryKey",[
     [java] 			]panelCategory.getKey...>
```

**Pull request closed without merging**
