### PR TITLE
LPS-172441

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar , could you please help me see what is wrong here when you have time?
Thanks!

**Comment by catarineaguiar** [comment]
@jeffwu0724 regression found on `:apps:analytics:analytics-dxp-entity-rest-impl:build`:

```
     [exec] > Task :apps:analytics:analytics-dxp-entity-rest-impl:buildREST FAILED
     [exec] Exception in thread "main" java.lang.NoClassDefFoundError: org/yaml/snakeyaml/error/MarkedYAMLException
     [exec] 	at com.liferay.portal.tools.rest.builder.RESTBuilder.<init>(RESTBuilder.java:143)
     [exec] 	at com.liferay.portal.tools.rest.builder.RESTBuilder.<init>(RESTBuilder.java:163)
     [exec] 	at com.liferay.portal.tools.rest.builder.RESTBuilder.main(RESTBuilder.java:112)
     [exec] Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.error.MarkedYAMLException
     [exec] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [exec] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [exec] 	... 3 more
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10517/rest-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
ci:test:sf

**Pull request closed without merging**
