### PR TITLE
change_compileInlcude_to_compileOnly_for_org.ow2.asm

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-169203.
I tried to change compileInclude to compileOnly for org.ow2.asm, because it is in shared-dependencies-asm already.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 
1)
com.liferay.knowledge.base.markdown.converter.internal.MarkdownConverterTest
com.liferay.knowledge.base.internal.importer.util.test.KBArticleMarkdownConverterTest
```
 com.liferay.knowledge.base.markdown.converter.internal.MarkdownConverterTest > testLiferayToHtmlSerializer FAILED
     [exec]     java.lang.RuntimeException: Error creating extended parser class: null
     [exec]         at org.parboiled.Parboiled.createParser(Parboiled.java:58)
     [exec]         at com.liferay.knowledge.base.markdown.converter.internal.pegdown.LiferayPegDownConverter.<init>(LiferayPegDownConverter.java:32)
     [exec]         at com.liferay.knowledge.base.markdown.converter.internal.pegdown.factory.MarkdownConverterFactoryImpl.create(MarkdownConverterFactoryImpl.java:31)
     [exec]         at com.liferay.knowledge.base.markdown.converter.internal.MarkdownConverterTest.testLiferayToHtmlSerializer(MarkdownConverterTest.java:47)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
[Log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-33/test-portal-acceptance-pullrequest(master)/2541/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

2) 
com.liferay.knowledge.base.service.test.KBArticleLocalServiceTest
```
 [exec] com.liferay.knowledge.base.service.test.KBArticleLocalServiceTest > testAddKBArticlesMarkdownWithNoWorkflow FAILED
     [exec]     java.lang.NoClassDefFoundError: org/pegdown/Parser
     [exec]     	at com.liferay.knowledge.base.markdown.converter.internal.pegdown.factory.MarkdownConverterFactoryImpl.create(MarkdownConverterFactoryImpl.java:31)
     [exec]     	at com.liferay.knowledge.base.internal.importer.util.MarkdownConverterFactoryUtil.create(MarkdownConverterFactoryUtil.java:30)
```
[Log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-39/test-portal-acceptance-pullrequest(master)/2117/modules-integration-mysql57-jdk8/2/6/jenkins-console.txt.gz?authuser=0)

3)Semver error
```
 [exec] > Task :apps:portal-security-sso:portal-security-sso-openid-connect-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.security.sso.openid.connect     MAJOR      4.0.0      5.0.0      6.0.0      VERSION INCREASE REQUIRED
     [exec] 	<   interface  com.liferay.portal.security.sso.openid.connect.OpenIdConnectAuthenticationHandler
     [exec] 		+   method     requestAuthentication(long,javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
     [exec] 			+   access     abstract
     [exec] 			+   return     void
     [exec] 	-   interface  com.liferay.portal.security.sso.openid.connect.OpenIdConnectProvider
     [exec] 		-   access     abstract
     [exec] 		-   method     getClientId()
```
[Log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-33/test-portal-acceptance-pullrequest(master)/2541/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
