### PR TITLE
LPS-149258

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@jeffwu0724 

- when I iniciated the portal with your changes the home page only displayed a search bar

- when I try to create a Report Admin with any kind of document it is not shown and this error is shown in the logs:
```
2022-07-19 18:22:52.406 ERROR [http-nio-8080-exec-5][PortletServlet:117] null
javax.portlet.PortletException: java.lang.IllegalStateException: Store is not available. Caller service needs to wait for store factory with "dl.store.impl.enabled=true".
	at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCActionCommand.processAction(BaseMVCActionCommand.java:65) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.callActionMethod(MVCPortlet.java:402) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.LiferayPortlet.processAction(LiferayPortlet.java:82) ~[portal-kernel.jar:?]
```
Steps to reproduce:

1. Go to configuration > Reports Admin
2. In Definitions tab click to add
3. Put a definition name
4. Choose a file on Report's Template
5. Save

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar , thanks for checking! May I ask if there is any other issue exists with this PR, please?

**Pull request closed without merging**
