### PR TITLE
LPS-149258

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar, could you please help me look at the test result when it is ready?
Thanks for your help!

**Comment by catarineaguiar** [comment]
@jeffwu0724 possible regressions:

```
  [exec] com.liferay.portal.tika.test.TextExtractorTest > testDoc FAILED
     [exec]     java.lang.NoClassDefFoundError: org/apache/commons/math3/util/ArithmeticUtils
     [exec]     	at org.apache.poi.poifs.property.RootProperty.setSize(RootProperty.java:59)
     [exec]     	at org.apache.poi.poifs.property.DirectoryProperty.<init>(DirectoryProperty.java:52)
     [exec]     	at org.apache.poi.poifs.property.RootProperty.<init>(RootProperty.java:31)
     [exec]     	at org.apache.poi.poifs.property.PropertyTable.<init>(PropertyTable.java:58)
     [exec]     	at org.apache.poi.poifs.filesystem.POIFSFileSystem.<init>(POIFSFileSystem.java:102)
     [exec]     	at org.apache.poi.poifs.filesystem.POIFSFileSystem.<init>(POIFSFileSystem.java:209)
     [exec]     	at org.apache.poi.poifs.filesystem.POIFSFileSystem.<init>(POIFSFileSystem.java:170)
     [exec]     	at org.apache.tika.parser.microsoft.POIFSContainerDetector.getTopLevelNames(POIFSContainerDetector.java:417)
     [exec]     	at org.apache.tika.parser.microsoft.POIFSContainerDetector.detect(POIFSContainerDetector.java:482)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-29/test-portal-acceptance-pullrequest(master)/4601/modules-integration-mysql57-jdk8/1/5/jenkins-console.txt.gz?authuser=0)

```
  [exec] com.liferay.batch.engine.internal.test.BatchEngineExportTaskExecutorTest > testExportBlogPostingsToXLSFileWithFieldNames FAILED
     [exec]     org.apache.poi.EmptyFileException: The supplied file was empty (zero bytes long)
     [exec]     	at org.apache.poi.util.IOUtils.peekFirstNBytes(IOUtils.java:111)
     [exec]     	at org.apache.poi.poifs.filesystem.FileMagic.valueOf(FileMagic.java:206)
     [exec]     	at org.apache.poi.openxml4j.opc.internal.ZipHelper.verifyZipHeader(ZipHelper.java:143)
     [exec]     	at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipStream(ZipHelper.java:175)
     [exec]     	at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:104)
     [exec]     	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:307)
     [exec]     	at org.apache.poi.ooxml.util.PackageHelper.open(PackageHelper.java:47)
     [exec]     	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:309)
     [exec]     	at com.liferay.batch.engine.internal.test.BatchEngineExportTaskExecutorTest._testExportBlogPostingsToXLSFile(BatchEngineExportTaskExecutorTest.java:584)
     [exec]     	at com.liferay.batch.engine.internal.test.BatchEngineExportTaskExecutorTest.testExportBlogPostingsToXLSFileWithFieldNames(BatchEngineExportTaskExecutorTest.java:260)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-29/test-portal-acceptance-pullrequest(master)/4601/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
[exec] com.liferay.batch.engine.internal.test.BatchEngineImportTaskExecutorTest > testCreateBlogPostingsFromCSVFile FAILED
     [exec]     java.lang.AssertionError: expected:<18> but was:<0>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:633)
     [exec]     	at com.liferay.batch.engine.internal.test.BatchEngineImportTaskExecutorTest._assertCreatedBlogPostings(BatchEngineImportTaskExecutorTest.java:474)
     [exec]     	at com.liferay.batch.engine.internal.test.BatchEngineImportTaskExecutorTest.testCreateBlogPostingsFromCSVFile(BatchEngineImportTaskExecutorTest.java:94)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-25/test-portal-acceptance-pullrequest(master)/4531/modules-integration-mysql57-jdk8/0/8/jenkins-console.txt.gz?authuser=0)

```
    [exec] 
     [exec] com.liferay.portal.reports.engine.console.jasper.internal.test.ReportEngineImplTest > testExportXls FAILED
     [exec]     java.lang.NoClassDefFoundError: com/zaxxer/sparsebits/SparseBitSet
     [exec]     	at org.apache.poi.ddf.EscherDggRecord.findNewDrawingGroupId(EscherDggRecord.java:304)
     [exec]     	at org.apache.poi.hssf.model.DrawingManager2.findNewDrawingGroupId(DrawingManager2.java:118)
     [exec]     	at org.apache.poi.hssf.usermodel.HSSFPatriarch.afterCreate(HSSFPatriarch.java:151)
     [exec]     	at org.apache.poi.hssf.usermodel.HSSFSheet.getPatriarch(HSSFSheet.java:2117)
     [exec]     	at org.apache.poi.hssf.usermodel.HSSFSheet.createDrawingPatriarch(HSSFSheet.java:2092)
     [exec]     	at net.sf.jasperreports.engine.export.JRXlsExporter.createSheet(JRXlsExporter.java:386)
     [exec]     	at net.sf.jasperreports.engine.export.JRXlsAbstractExporter.exportSheet(JRXlsAbstractExporter.java:1653)
     [exec]     	at net.sf.jasperreports.engine.export.JRXlsAbstractExporter.exportPage(JRXlsAbstractExporter.java:1084)
     [exec]     	at net.sf.jasperreports.engine.export.JRXlsAbstractExporter.exportEmptyReport(JRXlsAbstractExporter.java:2288)
     [exec]     	at net.sf.jasperreports.engine.export.JRXlsAbstractExporter.exportReportToStream(JRXlsAbstractExporter.java:1039)
     [exec]     	at net.sf.jasperreports.engine.export.JRXlsAbstractExporter.exportReport(JRXlsAbstractExporter.java:879)
     [exec]     	at com.liferay.portal.reports.engine.console.jasper.internal.exporter.BaseReportFormatExporter.format(BaseReportFormatExporter.java:44)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-29/test-portal-acceptance-pullrequest(master)/4601/modules-integration-mysql57-jdk8/1/8/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
