### PR TITLE
LPS-144892

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This PR is to fix https://issues.liferay.com/browse/LPS-144892
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result again, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@jeffwu0724 semver error:

```
[exec] [Baseline Warning] Bundle Version Change Recommended: 51.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/50.0.0/699f941963a31564f9d6c02e19e593fc4b9ca493/com.liferay.portal.kernel-50.0.0.jar
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-25/test-portal-acceptance-pullrequest(master)/2740/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
