### PR TITLE
update_xmlbeans

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@Kvale1733 can you check the results when it finish? Thanks!

**Comment by Kvale1733** [comment]
@zhangyan0701, Can you help check the results when they appear?

**Comment by zhangyan0701** [comment]
There are many startup errors like below:
```
 [parallel] 2022-09-22 20:12:36.874 ERROR [Framework Event Dispatcher: Equinox Container: 72542c76-a339-47a5-b8a6-38a135f252f3][Framework:56] FrameworkEvent ERROR
 [parallel] org.osgi.framework.BundleException: Could not resolve module: com.liferay.sharepoint.soap.repository [617]
 [parallel]   Unresolved requirement: Import-Package: org.apache.xmlbeans.impl.schema
 [parallel]     -> Export-Package: org.apache.xmlbeans.impl.schema; bundle-symbolic-name="com.liferay.shared.dependencies.xmlbeans"; bundle-version="1.0.0"; version="1.0.0"; uses:="javax.xml.namespace,javax.xml.stream,org.apache.xmlbeans,org.apache.xmlbeans.impl.regex,org.apache.xmlbeans.impl.repackage,org.apache.xmlbeans.impl.values,org.apache.xmlbeans.impl.xb.xsdschema,org.apache.xmlbeans.impl.xpath,org.apache.xmlbeans.soap,org.w3c.dom,org.xml.sax"
 [parallel]        com.liferay.shared.dependencies.xmlbeans [965]
 [parallel]          Unresolved requirement: Import-Package: com.github.javaparser
 [parallel]   Unresolved requirement: Import-Package: org.apache.xmlbeans
 [parallel]     -> Export-Package: org.apache.xmlbeans; bundle-symbolic-name="com.liferay.shared.dependencies.xmlbeans"; bundle-version="1.0.0"; version="1.0.0"; uses:="javax.xml.namespace,javax.xml.stream,org.apache.xmlbeans.impl.repackage,org.apache.xmlbeans.impl.schema,org.apache.xmlbeans.impl.store,org.w3c.dom,org.xml.sax,org.xml.sax.ext"
 [parallel] 
 [parallel] 	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi.jar:?]
```

Example console log:
https://testray.liferay.com/reports/production/logs/2022-09/test-1-29/test-portal-acceptance-pullrequest(master)/4714/functional-tomcat90-mysql57-jdk8/2/16/jenkins-console.txt.gz?authuser=0

**Pull request closed without merging**
