### PR TITLE
move_commons-math3_to_shared-dependencies

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hi @Kvale1733, 

Can you help me look at the test result, please? I didn't have the LPS ticket number in the commit message yet.
Thanks!

Jeff

**Comment by Kvale1733** [comment]
@jeffwu0724 Regressions found

1)
com.liferay.portal.reports.engine.console.jasper.internal.test.ReportEngineImplTest
com.liferay.dynamic.data.lists.exporter.test.DDLExporterTest
com.liferay.content.dashboard.web.internal.portlet.action.test.GetContentDashboardItemsXlsMVCResourceCommandTest

```
[exec]     java.lang.NoClassDefFoundError: org/apache/commons/math3/util/ArithmeticUtils
     [exec]     	at org.apache.poi.poifs.property.RootProperty.setSize(RootProperty.java:59)
     [exec]     	at org.apache.poi.poifs.property.DirectoryProperty.<init>(DirectoryProperty.java:52)
     [exec]     	at org.apache.poi.poifs.property.RootProperty.<init>(RootProperty.java:31)
```
[Example Log](https://testray.liferay.com/reports/production/logs/2022-10/test-1-39/test-portal-acceptance-pullrequest(master)/494/modules-integration-mysql57-jdk8/1/8/jenkins-console.txt.gz?authuser=0)

2) Re-index error causing all PortalSmokeUpgrade tests to fail
```
2022-10-05 21:18:29.414 WARN  [default-9][IndexerWriterImpl:197] Error reindexing all com.liferay.document.library.kernel.model.DLFileEntry for company: 20097
```
[Testray](https://testray.liferay.com/home/-/testray/case_results/1998447903)

Steps to reproduce:
    i. Import a legacy database like this one [7.3.10](https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.3.10/data-archive/data-archive-portal-mysql.zip)
    ii. Add **upgrade.database.auto.run=true** to portal-ext.properties 
    iii. Startup the portal
    iv. Go to Control Panel -> Search -> Index Actions
    v. Execute Reindex search indexes.
    
 Expected Results: Search Reindex is executed without error
 Actual Results: "Error reindexing all com.liferay.document.library.kernel.model.DLFileEntry for company: 20097" in logs

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hi @Kvale1733 , can you help me check the result again, please?
Thanks!

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Pull request closed without merging**
