### PR TITLE
LPS-187713

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar ,

Could you please help me check what is wrong here?
Thanks!

**Comment by jeffwu0724** [comment]
@catarineaguiar 
Thanks for finding the error! May I ask if it is possible to locate the root cause, please? Or may I ask about the reproduce step?

Thanks!

**Comment by catarineaguiar** [comment]
@jeffwu0724 so, I believe it can be reproduced just adding a new site, but it didn't show any error in the logs during the test. I don't know what caused it, but I saw you made some changes on site initializer, so it can be the cause.

Steps:

1. Go to Control panel > sites > click to add a new site
2. choose to create a blank site > add a name and add

expected result:
It might take a while loading to create the site, but it is created without errors

actual result:
an error message is shown and it seems that the site is not created

**Comment by catarineaguiar** [comment]
@jeffwu0724 So, some regressions were found on Functional tests:

**Unable to add a new web content**

Steps:
1. Go to product menu > content & data > Web content
2. Click to add a new basic web content > give it a name and a content > publish

Actual result: it keeps loading foverer and a warn is shown in the logs
```
2023-06-15 23:04:56.878 WARN  [http-nio-8080-exec-7][code_jsp:157] {code="400", msg="", uri=/o/dynamic-data-mapping-form-context-provider/}
```

**Unable to add a new blog**
Steps:

1. Go to product menu > content & data > Blogs
2. Click to add a new blog > give it a name and a content > publish

Actual result: an error displays `Please enter content with valid content size no larger than 0 B.`
No errors in the logs and the same error occurs when trying to add a new document and media

**Unable to add a new dynamic data list**

Steps:
1. Go to product menu > content & data > Dynamic Data Lists
2. Click to add  > give it a name and select any data definition > save

Actual result: an error displays `Please enter a valid definition.` and an error is shown in the logs
```
2023-06-15 23:30:03.025 ERROR [http-nio-8080-exec-9][StagingPermissionImpl:45] null
java.lang.NullPointerException: null
	at com.liferay.exportimport.internal.staging.permission.StagingPermissionImpl._hasPermission(StagingPermissionImpl.java:87) ~[?:?]
	at com.liferay.exportimport.internal.staging.permission.StagingPermissionImpl.hasPermission(StagingPermissionImpl.java:42) ~[?:?]
	at com.liferay.portal.kernel.security.permission.resource.StagedPortletPermissionLogic.contains(StagedPortletPermissionLogic.java:47) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.internal.security.permission.resource.DefaultPortletResourcePermission._contains(DefaultPortletResourcePermission.java:127) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.internal.security.permission.resource.DefaultPortletResourcePermission.lambda$contains$1(DefaultPortletResourcePermission.java:111) ~[portal-kernel.jar:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127) ~[?:1.8.0_221]
	at com.liferay.portal.kernel.internal.security.permission.resource.DefaultPortletResourcePermission.contains(DefaultPortletResourcePermission.java:102) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.internal.security.permission.resource.DefaultPortletResourcePermission.check(DefaultPortletResourcePermission.java:62) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.security.permission.resource.BasePortletResourcePermissionWrapper.check(BasePortletResourcePermissionWrapper.java:49) ~[portal-kernel.jar:?]
```

**error when selecting a liferay image**

Steps:
1. Go to product menu > content & data > Document & media
2. Go to provided by Liferay and click in some image checkbox

Actual result: an error is shown in the logs
```
2023-06-15 23:35:36.819 ERROR [http-nio-8080-exec-1][PortletRequestDispatcherImpl:304] Unable to dispatch request: com.liferay.portal.kernel.exception.NoSuchGroupException: No Group exists with the key {repositoryId=0}
2023-06-15 23:35:36.819 ERROR [http-nio-8080-exec-1][PortletServlet:118] Unable to process portlet com_liferay_document_library_web_portlet_DLAdminPortlet: javax.servlet.ServletException: com.liferay.portal.kernel.exception.NoSuchGroupException: No Group exists with the key {repositoryId=0}
javax.portlet.PortletException: javax.servlet.ServletException: com.liferay.portal.kernel.exception.NoSuchGroupException: No Group exists with the key {repositoryId=0}
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.dispatch(PortletRequestDispatcherImpl.java:307) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:123) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCResourceCommand.include(BaseMVCResourceCommand.java:84) ~[portal-kernel.jar:?]
	at com.liferay.document.library.web.internal.portlet.action.InfoPanelMVCResourceCommand.doServeResource(InfoPanelMVCResourceCommand.java:81) ~[bundleFile:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCResourceCommand.serveResource(BaseMVCResourceCommand.java:41) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.callResourceMethod(MVCPortlet.java:462) ~[portal-kernel.jar:?]
```

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
@catarineaguiar 
Thanks, Catarine, seems like the error we found before cannot reproduce locally now, but there are still other new regressions. Could you please help me check again?
Thanks!

**Comment by jeffwu0724** [comment]
Hey @Kvale1733 ,

Could you please help me check what is still wrong here when you have time, please?
Thanks

**Comment by Kvale1733** [comment]
@jeffwu0724 Regressions found

1) com.liferay.template.web.internal.portlet.action.test.UpdateTemplateEntryMVCActionCommandTest
```
 [exec] com.liferay.template.web.internal.portlet.action.test.UpdateTemplateEntryMVCActionCommandTest > testUpdateTemplateEntry FAILED
     [exec]     java.lang.RuntimeException: Unable to unwrap the portlet request from class com.liferay.portal.kernel.test.portlet.MockLiferayPortletActionRequest
     [exec]     	at com.liferay.portlet.LiferayPortletUtil.getLiferayPortletRequest(LiferayPortletUtil.java:49)
     [exec]     	at com.liferay.portal.upload.internal.UploadPortalImpl.getUploadPortletRequest(UploadPortalImpl.java:62)
     [exec]     	at com.liferay.template.web.internal.portlet.action.UpdateTemplateEntryMVCActionCommand.doTransactionalCommand(UpdateTemplateEntryMVCActionCommand.java:69)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-06/test-1-28/test-portal-acceptance-pullrequest(master)/6769/modules-integration-mysql57-jdk8/4/6/jenkins-console.txt.gz?authuser=0)

2) com.liferay.object.web.internal.portlet.action.test.ExportImportObjectDefinitionTest
```
 [exec] com.liferay.object.web.internal.portlet.action.test.ExportImportObjectDefinitionTest > testExportImportObjectDefinition FAILED
     [exec]     javax.portlet.PortletException: java.lang.NullPointerException
     [exec]     	at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCActionCommand.processAction(BaseMVCActionCommand.java:65)
     [exec]     	at com.liferay.object.web.internal.portlet.action.test.ExportImportObjectDefinitionTest._testExportImportObjectDefinition(ExportImportObjectDefinitionTest.java:216)
     [exec]     	at com.liferay.object.web.internal.portlet.action.test.ExportImportObjectDefinitionTest.testExportImportObjectDefinition(ExportImportObjectDefinitionTest.java:86)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-06/test-1-28/test-portal-acceptance-pullrequest(master)/6769/modules-integration-mysql57-jdk8/3/2/jenkins-console.txt.gz?authuser=0)

3) Semver issues
```
[exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.util                     MAJOR      60.0.0     60.0.0     61.0.0     VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.portal.kernel.util.PortalUtil
     [exec] 		-   method     getUploadPortletRequest(javax.portlet.PortletRequest)
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadPortletRequest
     [exec] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest)
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
     [exec] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest,int,java.lang.String)
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
     [exec] 	>   interface  com.liferay.portal.kernel.util.Portal
     [exec] 		-   method     getUploadPortletRequest(javax.portlet.PortletRequest)
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadPortletRequest
     [exec] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest)
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
     [exec] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest,int,java.lang.String)
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
     [exec] [Baseline Report] Mode: diff (persisted)
```

```
exec] > Task :baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.util                            MAJOR      49.0.0     49.0.0     50.0.0     VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.portal.util.PortalImpl
     [exec] 		-   method     getUploadPortletRequest(javax.portlet.PortletRequest)
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadPortletRequest
     [exec] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest)
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
     [exec] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest,int,java.lang.String)
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
```
[Log](https://testray.liferay.com/reports/production/logs/2023-06/test-1-28/test-portal-acceptance-pullrequest(master)/6769/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

4) Compile issue
```
   [exec] > Task :apps:staging:staging-taglib:jarTLDDoc
     [exec] > Task :apps:staging:staging-taglib:assemble
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/static/portal-osgi-web/portal-osgi-web-portlet-container-test/src/testIntegration/java/com/liferay/portal/osgi/web/portlet/container/upload/portlet/request/test/UploadPortletRequestWhenGettingSizeTest.java:24: error: cannot find symbol
     [exec] import com.liferay.portal.upload.UploadPortletRequestImpl;
     [exec]                                 ^
     [exec]   symbol:   class UploadPortletRequestImpl
     [exec]   location: package com.liferay.portal.upload
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/static/portal-osgi-web/portal-osgi-web-portlet-container-test/src/testIntegration/java/com/liferay/portal/osgi/web/portlet/container/upload/portlet/request/test/UploadPortletRequestWhenGettingSizeTest.java:68: error: cannot find symbol
     [exec] 			new UploadPortletRequestImpl(
     [exec] 			    ^
     [exec]   symbol:   class UploadPortletRequestImpl
     [exec]   location: class com.liferay.portal.osgi.web.portlet.container.upload.portlet.request.test.UploadPortletRequestWhenGettingSizeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/static/portal-osgi-web/portal-osgi-web-portlet-container-test/src/testIntegration/java/com/liferay/portal/osgi/web/portlet/container/upload/portlet/request/test/UploadPortletRequestWhenGettingSizeTest.java:97: error: cannot find symbol
     [exec] 			new UploadPortletRequestImpl(
     [exec] 			    ^
     [exec]   symbol:   class UploadPortletRequestImpl
     [exec]   location: class com.liferay.portal.osgi.web.portlet.container.upload.portlet.request.test.UploadPortletRequestWhenGettingSizeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/static/portal-osgi-web/portal-osgi-web-portlet-container-test/src/testIntegration/java/com/liferay/portal/osgi/web/portlet/container/upload/portlet/request/test/UploadPortletRequestWhenGettingSizeTest.java:122: error: cannot find symbol
     [exec] 			new UploadPortletRequestImpl(
     [exec] 			    ^
     [exec]   symbol:   class UploadPortletRequestImpl
     [exec]   location: class com.liferay.portal.osgi.web.portlet.container.upload.portlet.request.test.UploadPortletRequestWhenGettingSizeTest
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/static/portal-osgi-web/portal-osgi-web-portlet-container-test/src/testIntegration/java/com/liferay/portal/osgi/web/portlet/container/test/PublicRenderParameterTest.java uses or overrides a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] 4 errors
     [exec] > Task :apps:static:portal-osgi-web:portal-osgi-web-wab-generator-impl:jar
     [exec] > Task :apps:static:portal-osgi-web:portal-osgi-web-wab-generator-impl:autoUpdateXml SKIPPED
     [exec] 
```
[Log](https://testray.liferay.com/reports/production/logs/2023-06/test-1-28/test-portal-acceptance-pullrequest(master)/6769/modules-compile-jdk8/0/4/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Pull request closed without merging**
