### PR TITLE
LPS-176787 upgrade Apache Commons FileUpload to 1.15

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, 

This is for ticket https://issues.liferay.com/browse/LPS-176787.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
curl -X POST -u 'jiefeng.wu@liferay.com:test1' -F 'externalReferenceCode=' -F 'repositoryId=20120' -F 'folderId=0' -F 'sourceFileName=Document_1.txt' -F 'mimeType=text/plain' -F 'title=DM Document Title' -F 'urlTitle=' -F 'description=DM Document Description' -F 'changeLog=' -F 'file=portal-web/test/functional/com/liferay/portalweb/dependencies/Document_1.txt' -F 'serviceContext={"addGroupPermissions" : true, "addGuestPermissions": true}' http://localhost:8080/api/jsonws/dlapp/add-file-entry


curl -X POST -u 'jiefeng.wu@liferay.com:test1' -F 'externalReferenceCode=' -F 'repositoryId=20120' -F 'folderId=0' -F 'sourceFileName=Document_1.txt' -F 'mimeType=text/plain' -F 'title=DM Document Title' -F 'urlTitle=' -F 'description=DM Document Description' -F 'changeLog=' -F 'file=@test/functional/com/liferay/portalweb/dependencies/Document_1.txt' -F 'serviceContext={"addGroupPermissions" : true, "addGuestPermissions": true}' http://localhost:8080/api/jsonws/dlapp/add-file-entry

**Comment by jeffwu0724** [comment]
Hey @Kvale1733 , could you please help me check the result when you have time? 
FYI, https://github.com/liferay-core-infra/liferay-portal/pull/3677#issuecomment-1454110803
Thanks

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions. The failing document tests are now passing so the issue from the previous PR is fixed.

**Comment by jeffwu0724** [comment]
@Kvale1733 Yay, thanks Kevin!! :D

**Pull request closed without merging**
