### PR TITLE
LPS-157036

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-157036 and https://issues.liferay.com/browse/LPS-157039.
Thanks for checking.

for reference https://github.com/shuyangzhou/liferay-portal/pull/9537/commits
https://github.com/brianchandotcom/liferay-portal/pull/68979/commits

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
ci:test:environment

**Comment by jeffwu0724** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
manually triggered `smoke` suite with modifications on CI to force TLSv1.2

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@jeffwu0724 Fix was merged on Jenkins side

@Kvale1733 Please check the new test results when they come in.

**Comment by Kvale1733** [comment]
Waiting for testray results to publish: https://test-1-38.liferay.com/job/publish-testray-report/5308/

**Comment by Kvale1733** [comment]
@jeffwu0724  no regressions found.

**Pull request closed without merging**
