### PR TITLE
only_client_page.ftl

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @zhangyan0701 , could you please help me see what is wrong here, please?

**Comment by zhangyan0701** [comment]
ci:test:bundle

**Comment by zhangyan0701** [comment]
There are many integration tests failed with error like below:
`java.lang.IllegalArgumentException: Unsupported field name actions`

Example: [com.liferay.headless.admin.workflow.resource.v1_0.test.WorkflowTaskTransitionsResourceTest](https://testray.liferay.com/home/-/testray/case_results/2205549906)
Full console: https://testray.liferay.com/reports/production/logs/2023-02/test-1-29/test-portal-acceptance-pullrequest(master)/6434/modules-integration-mysql57-jdk8/0/21/jenkins-console.txt.gz?authuser=0

**Pull request closed without merging**
