### PR TITLE
props_get

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
@jeffwu0724 

```
format-source-files:
     [java] java.lang.Exception: Found formatting issues:
     [java] At least one commit message is missing a reference to a required JIRA project: BLADE, CLDSVCS, COMMERCE, FACES, IDE, LCD, LHC, LOOP, LPS, LRAC, LRCI, LRDOCS, LRIS, LRQA, OAUTH2, POSHI, RELEASE, SYNC, TR. Please verify that the JIRA project keys are specifiedin ci.properties in the liferay-portal repository.
     [java] 	at com.liferay.source.formatter.util.JIRAUtil.validateJIRAProjectNames(JIRAUtil.java:71)
     [java] 	at com.liferay.source.formatter.SourceFormatter._validateCommitMessages(SourceFormatter.java:1276)
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:320)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:284)
[stopwatch] [run.batch.test.action: 59.956 sec]
```

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@jeffwu0724 all functional tests failed with these references in the logs:

```
 [junit] Testcase: testScanXMLLog(com.liferay.portal.log.assertor.PortalLogAssertorTest):	FAILED
    [junit] 
    [junit] Portal log assert failure, see above log for more information: 
    [junit] bundle com.liferay.portal.lpkg.deployer.impl:4.0.16 (25)[com.liferay.portal.lpkg.deployer.internal.LPKGBundleTrackerCustomizer(15)] : Constructor with 0 arguments not found. Component will fail.
    [junit] junit.framework.AssertionFailedError: 
    [junit] bundle com.liferay.portal.lpkg.deployer.impl:4.0.16 (25)[com.liferay.portal.lpkg.deployer.internal.LPKGBundleTrackerCustomizer(15)] : Constructor with 0 arguments not found. Component will fail.
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:171)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:86)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-25/test-portal-acceptance-pullrequest(master)/4667/functional-smoke-wildfly180-mariadb104-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

Failure on the portal startup:
```
 [exec] 2022-09-20 19:19:16.306 INFO  [ModuleFramework-Static-Bundles-10][InterpolationConfigurationPlugin:109] Configured directory for secrets: /opt/dev/projects/github/liferay-portal/dist/20220920121909514/liferay-portal-7.4.13.u43/osgi/configs
     [exec] 2022-09-20 19:19:16.562 ERROR [ModuleFramework-Static-Bundles-1][LPKGBundleTrackerCustomizer:370] Rollback bundle installation for [com.liferay.json.storage.service_1.0.15 [91]]
     [exec] java.lang.NullPointerException: null
     [exec] 	at com.liferay.portal.lpkg.deployer.internal.LPKGBundleTrackerCustomizer.addingBundle(LPKGBundleTrackerCustomizer.java:352) ~[?:?]
     [exec] 	at com.liferay.portal.lpkg.deployer.internal.LPKGBundleTrackerCustomizer.addingBundle(LPKGBundleTrackerCustomizer.java:95) ~[?:?]
     [exec] 	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:475) ~[org.eclipse.osgi.jar:?]
     [exec] 	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1) ~[org.eclipse.osgi.jar:?]
     [exec] 	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[org.eclipse.osgi.jar:?]
     [exec] 	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) ~[org.eclipse.osgi.jar:?]
     [exec] 	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450) ~[org.eclipse.osgi.jar:?]
     [exec] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908) ~[org.eclipse.osgi.jar:?]
     [exec] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) ~[org.eclipse.osgi.jar:?]
     [exec] 	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) ~[org.eclipse.osgi.jar:?]
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:230) ~[org.eclipse.osgi.jar:?]
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:137) ~[org.eclipse.osgi.jar:?]
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:129) ~[org.eclipse.osgi.jar:?]
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:191) ~[org.eclipse.osgi.jar:?]
     [exec] 	at org.eclipse.osgi.container.ModuleContainer.install(ModuleContainer.java:299) ~[org.eclipse.osgi.jar:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-25/test-portal-acceptance-pullrequest(master)/4667/portal-license-smoke-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
