### PR TITLE
LPS-154824

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

FYI, based on https://axis.apache.org/axis2/java/core//release-notes/1.8.0.html, axis2 is still using httpclient3, and I updated it to newest version, which will have a dependency on httpclient4.
This is for https://issues.liferay.com/browse/LPS-154824.
I also removed the two third-party patch because they are fixed in the newer version.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result again, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
Hi @jeffwu0724, the `SharepointConnectionTest` unit test failed:

```
 [exec] com.liferay.sharepoint.soap.repository.connector.SharepointConnectionTest > classMethod FAILED
     [exec]     java.lang.NoClassDefFoundError: org/apache/commons/httpclient/auth/AuthScope
     [exec]         at org.apache.axis2.transport.http.impl.httpclient3.HttpTransportPropertiesImpl$Authenticator.<init>(HttpTransportPropertiesImpl.java:54)
     [exec]         at com.liferay.sharepoint.soap.repository.connector.SharepointConnectionImpl._configureStub(SharepointConnectionImpl.java:357)
     [exec]         at com.liferay.sharepoint.soap.repository.connector.SharepointConnectionImpl._initCopyStub(SharepointConnectionImpl.java:387)
     [exec]         at com.liferay.sharepoint.soap.repository.connector.SharepointConnectionImpl.<init>(SharepointConnectionImpl.java:85)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-06/test-1-28/test-portal-acceptance-pullrequest(master)/3270/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
ci:test:sf

**Pull request closed without merging**
