### PR TITLE
Test

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar , could you please help me check the test result? 
Thanks!

**Comment by catarineaguiar** [comment]
@jeffwu0724 regressions:

semver error:
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/object/object-rest-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.object.rest.dto.v1_0.util              MAJOR      1.0.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.object.rest.dto.v1_0.util.CreatorUtil
     [exec]     		-   method     toCreator(com.liferay.portal.kernel.util.Portal,java.util.Optional,com.liferay.portal.kernel.model.User)
     [exec]     			-   access     static
     [exec]     			-   return     com.liferay.headless.delivery.dto.v1_0.Creator
     [exec]     		+   method     toCreator(com.liferay.portal.kernel.util.Portal,javax.ws.rs.core.UriInfo,com.liferay.portal.kernel.model.User)
     [exec]     			+   access     static
     [exec]     			+   return     com.liferay.headless.delivery.dto.v1_0.Creator
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 12.0.0
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-27/test-portal-acceptance-pullrequest(master)/6359/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.object.admin.rest.resource.v1_0.test.ObjectActionResourceTest > testGetObjectDefinitionByExternalReferenceCodeObjectActionsPage FAILED
     [exec]     java.lang.UnsupportedOperationException: This method needs to be implemented
     [exec]     	at com.liferay.object.admin.rest.resource.v1_0.test.BaseObjectActionResourceTestCase.testGetObjectDefinitionByExternalReferenceCodeObjectActionsPage_getExternalReferenceCode(BaseObjectActionResourceTestCase.java:517)
     [exec]     	at com.liferay.object.admin.rest.resource.v1_0.test.BaseObjectActionResourceTestCase.testGetObjectDefinitionByExternalReferenceCodeObjectActionsPage(BaseObjectActionResourceTestCase.java:395)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
```
          [exec] com.liferay.object.rest.internal.manager.v1_0.test.DefaultObjectEntryManagerImplTest > testAddObjectEntry STARTED
[beanshell] 2022-12-29 08:41:27.953 ERROR [com.liferay.object.rest.test-executor-thread][ObjectEntryUtil:123] null
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.object.rest.dto.v1_0.util.CreatorUtil$1.lambda$new$1(CreatorUtil.java:63) ~[?:?]
[beanshell] 	at com.liferay.headless.delivery.dto.v1_0.Creator.setProfileURL(Creator.java:272) ~[?:?]
[beanshell] 	at com.liferay.object.rest.dto.v1_0.util.CreatorUtil$1.<init>(CreatorUtil.java:60) ~[?:?]
[beanshell] 	at com.liferay.object.rest.dto.v1_0.util.CreatorUtil.toCreator(CreatorUtil.java:37) ~[?:?]
```
```
     [exec] com.liferay.object.rest.internal.manager.v1_0.test.DefaultObjectEntryManagerImplTest > testAddObjectEntry FAILED
     [exec]     java.lang.NullPointerException
     [exec]     	at com.liferay.object.rest.dto.v1_0.util.CreatorUtil$1.lambda$new$1(CreatorUtil.java:63)
     [exec]     	at com.liferay.headless.delivery.dto.v1_0.Creator.setProfileURL(Creator.java:272)
     [exec]     	at com.liferay.object.rest.dto.v1_0.util.CreatorUtil$1.<init>(CreatorUtil.java:60)
     [exec]     	at com.liferay.object.rest.dto.v1_0.util.CreatorUtil.toCreator(CreatorUtil.java:37)
     [exec]     	at com.liferay.object.rest.internal.dto.v1_0.converter.ObjectEntryDTOConverter$2.<init>(ObjectEntryDTOConverter.java:286)
     [exec]     	at com.liferay.object.rest.internal.dto.v1_0.converter.ObjectEntryDTOConverter._toDTO(ObjectEntryDTOConverter.java:283)
     [exec]     	at com.liferay.object.rest.internal.dto.v1_0.converter.ObjectEntryDTOConverter.toDTO(ObjectEntryDTOConverter.java:110)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-27/test-portal-acceptance-pullrequest(master)/6359/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

```
    [exec] com.liferay.object.rest.internal.vulcan.extension.v1_0.test.ObjectRelationshipExtensionProviderTest > testGetExtendedProperties FAILED
     [exec]     java.lang.RuntimeException: java.lang.NullPointerException
     [exec]     	at com.liferay.petra.function.transform.TransformUtil.transform(TransformUtil.java:37)
     [exec]     	at com.liferay.object.rest.internal.manager.v1_0.DefaultObjectEntryManagerImpl._toObjectEntries(DefaultObjectEntryManagerImpl.java:890)
     [exec]     	at com.liferay.object.rest.internal.manager.v1_0.DefaultObjectEntryManagerImpl._getSystemObjectRelatedObjectEntries(DefaultObjectEntryManagerImpl.java:748)
     [exec]     	at com.liferay.object.rest.internal.manager.v1_0.DefaultObjectEntryManagerImpl.getObjectEntryRelatedObjectEntries(DefaultObjectEntryManagerImpl.java:530)
```
```
     [exec] com.liferay.object.graphql.test.ObjectDefinitionGraphQLTest > testGetListObjectEntry FAILED
     [exec]     org.junit.ComparisonFailure: expected:<[peter@liferay.com]> but was:<[null]>
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:117)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
     [exec]     	at com.liferay.object.graphql.test.ObjectDefinitionGraphQLTest.testGetListObjectEntry(ObjectDefinitionGraphQLTest.java:222)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-27/test-portal-acceptance-pullrequest(master)/6359/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Pull request closed without merging**
