### PR TITLE
LPS-149258

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Updated based on discussion in https://github.com/liferay-core-infra/liferay-portal/pull/803
This is for ticket https://issues.liferay.com/browse/LPS-149258.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
@jeffwu0724 some regressions were found:

`TextExtractorTest`
```
com.liferay.portal.tika.test.TextExtractorTest > testDoc FAILED
    java.lang.NoSuchFieldError: WORKBOOK_DIR_ENTRY_NAMES
    	at org.apache.tika.parser.microsoft.POIFSContainerDetector.detect(POIFSContainerDetector.java:214)
    	at org.apache.tika.parser.microsoft.POIFSContainerDetector.detect(POIFSContainerDetector.java:489)
    	at org.apache.tika.detect.CompositeDetector.detect(CompositeDetector.java:84)
    	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:116)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-27/test-portal-acceptance-pullrequest(master)/3453/modules-integration-mysql57-jdk8/3/4/jenkins-console.txt.gz?authuser=0)

`ReportEngineImplTest`
```
com.liferay.portal.reports.engine.console.jasper.internal.test.ReportEngineImplTest > testExportXls FAILED
    java.lang.NoClassDefFoundError: com/zaxxer/sparsebits/SparseBitSet
    	at org.apache.poi.ddf.EscherDggRecord.findNewDrawingGroupId(EscherDggRecord.java:304)
    	at org.apache.poi.hssf.model.DrawingManager2.findNewDrawingGroupId(DrawingManager2.java:81)
    	at org.apache.poi.hssf.usermodel.HSSFPatriarch.afterCreate(HSSFPatriarch.java:151)
    	at org.apache.poi.hssf.usermodel.HSSFSheet.getPatriarch(HSSFSheet.java:2118)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-27/test-portal-acceptance-pullrequest(master)/3453/modules-integration-mysql57-jdk8/4/0/jenkins-console.txt.gz?authuser=0)

`DDLTest`, `BatchEngineImportTaskExecutorTest`
```
com.liferay.dynamic.data.lists.util.test.DDLTest > classMethod FAILED
    org.osgi.framework.BundleException: Could not resolve module: com.liferay.dynamic.data.lists.test [1457]
      Unresolved requirement: Import-Package: com.github.javaparser
        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:447)
        at com.liferay.arquillian.extension.junit.bridge.connector.FrameworkCommand.lambda$startBundle$37e16ea2$1(FrameworkCommand.java:46)
        at com.liferay.arquillian.extension.junit.bridge.connector.ArquillianConnectorThread.run(ArquillianConnectorThread.java:82)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-27/test-portal-acceptance-pullrequest(master)/3453/modules-integration-mysql57-jdk8/1/12/jenkins-console.txt.gz?authuser=0)

`XLSBatchEngineExportTaskItemWriterImplTest`
```
com.liferay.batch.engine.internal.writer.XLSBatchEngineExportTaskItemWriterImplTest > testWriteRowsWithEmptyFieldNames FAILED
    java.lang.NoClassDefFoundError: Could not initialize class org.openxmlformats.schemas.spreadsheetml.x2006.main.CTWorkbook
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.onWorkbookCreate(XSSFWorkbook.java:475)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:232)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:226)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:214)
        at com.liferay.batch.engine.internal.writer.XLSBatchEngineExportTaskItemWriterImpl.<init>(XLSBatchEngineExportTaskItemWriterImpl.java:116)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-27/test-portal-acceptance-pullrequest(master)/3453/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

`XLSBatchEngineExportTaskItemWriterImplTest`
```
com.liferay.batch.engine.internal.writer.XLSBatchEngineExportTaskItemWriterImplTest > testWriteRowsWithDefinedFieldNames1 FAILED
    java.lang.NoClassDefFoundError: org/apache/xmlbeans/impl/schema/DocumentFactory
        at org.openxmlformats.schemas.spreadsheetml.x2006.main.CTWorkbook.<clinit>(CTWorkbook.java:22)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.onWorkbookCreate(XSSFWorkbook.java:475)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:232)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:226)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-27/test-portal-acceptance-pullrequest(master)/3453/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
