### PR TITLE
LPS-183594

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @zhangyan0701 ,

Could you please help me check if this PR has any regression?
Thanks!

**Comment by zhangyan0701** [comment]
Hi @jeffwu0724 

There are some integration tests failed with errors like below:
```
java.lang.ExceptionInInitializerError
... ...
Caused by: java.lang.NullPointerException
at com.liferay.portal.upload.test.util.UploadTestUtil.<clinit>(UploadTestUtil.java:50)
```
Or
```
java.lang.NoClassDefFoundError: Could not initialize class com.liferay.portal.upload.test.util.UploadTestUtil
```
Example:
[com.liferay.portal.osgi.web.portlet.container.upload.portlet.request.test.UploadPortletRequestWhenGettingSizeTest](https://testray.liferay.com/home/-/testray/case_results/2322493510)
Full console log:
https://testray.liferay.com/reports/production/logs/2023-05/test-1-40/test-portal-acceptance-pullrequest(master)/2715/modules-integration-mysql57-jdk8/4/3/jenkins-console.txt.gz?authuser=0

And there is a semantic versioning issue:
```
     [exec] > Task :baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.util                     MAJOR      60.0.0     60.0.0     61.0.0     VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.portal.kernel.util.PortalUtil
     [exec] 		-   method     getUploadPortletRequest(javax.portlet.PortletRequest)
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadPortletRequest
     [exec] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest)
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
     [exec] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest,int,java.lang.String)
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
     [exec] 	>   interface  com.liferay.portal.kernel.util.Portal
     [exec] 		-   method     getUploadPortletRequest(javax.portlet.PortletRequest)
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadPortletRequest
     [exec] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest)
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
     [exec] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest,int,java.lang.String)
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
     [exec] [Baseline Warning] Bundle Version Change Recommended: 111.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/110.0.0/e911bc3bb0a043eeb853dc8be9a0159fe600604d/com.liferay.portal.kernel-110.0.0.jar
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-05/test-1-40/test-portal-acceptance-pullrequest(master)/2715/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
Hey @zhangyan0701 ,

I have fixed the regression, and cannot reproduce locally. Could you please help me check again?
Thanks!

**Comment by zhangyan0701** [comment]
Hi @jeffwu0724 

The semantic versioning issue still exists:
```
     [exec] > Task :baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.util                     MAJOR      60.0.0     60.0.0     61.0.0     VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.portal.kernel.util.PortalUtil
     [exec] 		-   method     getUploadPortletRequest(javax.portlet.PortletRequest)
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadPortletRequest
     [exec] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest)
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
     [exec] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest,int,java.lang.String)
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
     [exec] 	>   interface  com.liferay.portal.kernel.util.Portal
     [exec] 		-   method     getUploadPortletRequest(javax.portlet.PortletRequest)
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadPortletRequest
     [exec] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest)
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
     [exec] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest,int,java.lang.String)
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/110.0.0/e911bc3bb0a043eeb853dc8be9a0159fe600604d/com.liferay.portal.kernel-110.0.0.jar
```
Full console log;
https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8385/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

Other failures are unrelated, no regressions found.

**Pull request closed without merging**
