### PR TITLE
remove_optional_in_portal_search

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @Kvale1733, could you please help me check what goes wrong, please?

**Comment by Kvale1733** [comment]
@jeffwu0724 There is a startup issue
```
[beanshell] 2023-01-24 02:26:16.113 INFO  [Portal Dependency Manager Component Executor--1][BundleSiteInitializer:4272] Invoking line 432 in 0 ms
[beanshell] 2023-01-24 02:26:16.185 ERROR [Portal Dependency Manager Component Executor--1][BundleSiteInitializer:550] null
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.portal.search.internal.util.SearchStringUtil.splitAndUnquote(SearchStringUtil.java:49) ~[?:?]
[beanshell] 	at com.liferay.portal.search.internal.indexer.helper.PreFilterContributorHelperImpl.getStrings(PreFilterContributorHelperImpl.java:107) ~[?:?]
[beanshell] 	at com.liferay.portal.search.internal.indexer.helper.PreFilterContributorHelperImpl._addPreFilters(PreFilterContributorHelperImpl.java:188) ~[?:?]
[beanshell] 	at com.liferay.portal.search.internal.indexer.helper.PreFilterContributorHelperImpl.contribute(PreFilterContributorHelperImpl.java:62) ~[?:?]
[beanshell] 	at com.liferay.portal.search.internal.indexer.IndexerQueryBuilderImpl._addPreFilters(IndexerQueryBuilderImpl.java:193) ~[?:?]
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-26/test-portal-acceptance-pullrequest(master)/7193/functional-smoke-tomcat90-mysql57-jdk11_open/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@jeffwu0724 Regression in
BatchIndexingHelperImplBulkSizesTest
```
[exec] com.liferay.portal.search.internal.batch.BatchIndexingHelperImplBulkSizesTest > testMalformed FAILED
     [exec]     java.lang.ArrayIndexOutOfBoundsException: 0
     [exec]         at com.liferay.portal.search.internal.batch.BatchIndexingHelperImpl.getBulkS
```
```
  [exec] com.liferay.portal.search.internal.batch.BatchIndexingHelperImplBulkSizesTest > testDefaultWithConfiguration FAILED
     [exec]     java.lang.AssertionError: expected:<10000> but was:<200>
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.failNotEquals(Assert.java:834)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-26/test-portal-acceptance-pullrequest(master)/7193/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
Hi @Kvale1733 , may I ask if there is still any regression, please?

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions.

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@jeffwu0724 Hmm seems this regression is showing up again. 
com.liferay.portal.search.internal.batch.BatchIndexingHelperImplBulkSizesTest 
```
 [exec] com.liferay.portal.search.internal.batch.BatchIndexingHelperImplBulkSizesTest > testMalformed FAILED
     [exec]     java.lang.ArrayIndexOutOfBoundsException: 0
     [exec]         at com.liferay.portal.search.internal.batch.BatchIndexingHelperImpl.getBulkSize(BatchIndexingHelperImpl.java:49)
     [exec]         at com.liferay.portal.search.internal.batch.BatchIndexingHelperImplBulkSizesTest._assertBulkSize(BatchIndexingHelperImplBulkSizesTest.java:90)
     [exec]         at com.liferay.portal.search.internal.batch.BatchIndexingHelperImplBulkSizesTest.testMalformed(BatchIndexingHelperImplBulkSizesTest.java:74)
```
```
 [exec] com.liferay.portal.search.internal.batch.BatchIndexingHelperImplBulkSizesTest > testDefaultWithConfiguration FAILED
     [exec]     java.lang.AssertionError: expected:<10000> but was:<200>
     [exec]         at org.junit.Assert.fail(Assert.java:88)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-39/test-portal-acceptance-pullrequest(master)/2553/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
@Kvale1733 , thanks! Seems like I push the wrong version :(

**Pull request closed without merging**
