### PR TITLE
remove_deprecated_for_portal_kernel_part_Nine

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test
ci:test:relevant
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar can you help me check this pr, please?

**Comment by catarineaguiar** [comment]
Hey @jeffwu0724, there is a regression and  you can run the integration test `com.liferay.asset.publisher.exportimport.test.AssetPublisherExportImportTest` to see it. It is affecting several functional tests, but the manual steps are slightly complex and throw the same error as the integration test.

``` 
com.liferay.journal.asset.test.JournalArticleAssetSearchTest > testOrderByTitleAsc FAILED
    java.lang.StackOverflowError
    	at com.liferay.portal.search.internal.sort.SortFieldBuilderImpl.getSortField(SortFieldBuilderImpl.java:48)
    	at com.liferay.portal.search.internal.sort.SortFieldBuilderImpl._getSortField(SortFieldBuilderImpl.java:120)
```

**Pull request closed without merging**
