### PR TITLE
remove_stream_and_optional_in_headless_delivery_api

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @Kvale1733 , could you please help me check what did I break, please?

**Comment by Kvale1733** [comment]
@jeffwu0724 Looks like there is an issue at startup. The portal isn't initialized correctly and throws an NPE.
```
[beanshell] 2023-03-08 23:32:59.648 INFO  [Portal Dependency Manager Component Executor--1][BundleSiteInitializer:410] Initializing com.liferay.site.initializer.welcome for group 20120
[beanshell] 2023-03-08 23:32:59.650 INFO  [Portal Dependency Manager Component Executor--1][BundleSiteInitializer:4374] Invoking line 436 took 2 ms
[beanshell] 2023-03-08 23:32:59.651 INFO  [Portal Dependency Manager Component Executor--1][BundleSiteInitializer:4393] Invoking line 439 in 1 ms
[beanshell] 2023-03-08 23:32:59.652 INFO  [Portal Dependency Manager Component Executor--1][BundleSiteInitializer:4374] Invoking line 441 took 1 ms
[beanshell] 2023-03-08 23:32:59.653 INFO  [Portal Dependency Manager Component Executor--1][BundleSiteInitializer:4393] Invoking line 444 in 0 ms
[beanshell] 2023-03-08 23:33:00.008 ERROR [Portal Dependency Manager Component Executor--1][BundleSiteInitializer:581] null
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.headless.delivery.dto.v1_0.util.CreatorUtil$1.lambda$new$1(CreatorUtil.java:63) ~[?:?]
[beanshell] 	at com.liferay.headless.delivery.dto.v1_0.Creator.setProfileURL(Creator.java:272) ~[?:?]
[beanshell] 	at com.liferay.headless.delivery.dto.v1_0.util.CreatorUtil$1.<init>(CreatorUtil.java:60) ~[?:?]
[beanshell] 	at com.liferay.headless.delivery.dto.v1_0.util.CreatorUtil.toCreator(CreatorUtil.java:37) ~[?:?]
[beanshell] 	at com.liferay.headless.delivery.internal.dto.v1_0.converter.DocumentFolderDTOConverter$1.<init>(DocumentFolderDTOConverter.java:63) ~[?:?]
[beanshell] 	at com.liferay.headless.delivery.internal.dto.v1_0.converter.DocumentFolderDTOConverter.toDTO(DocumentFolderDTOConverter.java:59) ~[?:?]
[beanshell] 	at com.liferay.headless.delivery.internal.resource.v1_0.DocumentFolderResourceImpl._toDocumentFolder(DocumentFolderResourceImpl.java:406) ~[?:?]
[beanshell] 	at com.liferay.headless.delivery.internal.resource.v1_0.DocumentFolderResourceImpl._addDocumentFolder(DocumentFolderResourceImpl.java:336) ~[?:?]
[beanshell] 	at com.liferay.headless.delivery.internal.resource.v1_0.DocumentFolderResourceImpl.postSiteDocumentFolder(DocumentFolderResourceImpl.java:263) ~[?:?]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
```
[Log](https://testray.liferay.com/reports/production/logs/2023-03/test-1-35/test-portal-acceptance-pullrequest(master)/3813/functional-smoke-tomcat90-db2115-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Pull request closed without merging**
