### PR TITLE
JDK17 local fixes

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
Hi @jeffwu0724, could you trigger a run on this PR, and another run without https://github.com/jeffwu0724/liferay-portal/pull/589/commits/d837eef94f48a172bc22fb5a065cca34c6e5d019?

**Comment by jeffwu0724** [comment]
Hi @dantewang ,

I have triggered a test for this PR, and also a tets without https://github.com/jeffwu0724/liferay-portal/commit/d837eef94f48a172bc22fb5a065cca34c6e5d019 in https://github.com/jeffwu0724/liferay-portal/pull/590#issuecomment-2561236197
For this commit, I have asked Victor before, he would like us to stick with jdk 8 for poshi as he said "Poshi with JDK8 unless you can tell me why it must be 17"

cc: @vicnate5  @tinatian

**Comment by jeffwu0724** [comment]
Hi @dantewang 
This is the comparison between the acceptance-dxp in this PR and upstream jdk 8, please see https://testray.liferay.com/#/compare-runs/99351185/99620332/details?filter=%7B%22testrayCaseResultStatus1%22%3A%5B%22PASSED%22%5D%2C%22testrayCaseResultStatus2%22%3A%5B%22FAILED%22%5D%7D&filterSchema=compareRunsCases&page=1

**Comment by dantewang** [comment]
@jeffwu0724 @vicnate5

- LocalFile.BundleBlacklist#BlacklistModuleLPKG
- LocalFile.DatabaseUpgradeClient#CheckUpgradeClientGogoShellHelpOutput

These 2 tests failed in #590, but passed in this PR. I added this https://github.com/jeffwu0724/liferay-portal/pull/589/commits/d837eef94f48a172bc22fb5a065cca34c6e5d019 just for these 2 cases. Generally, they both run ant targets compiling something and failed because of the globally configured source/target version 17. If we want to keep Poshi running in JDK8, we need to provide a way to run these compilation (or all ant invocations) to use the JDK version matching the portal source.

**Pull request closed without merging**
