### PR TITLE
LPS-149258

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
@jeffwu0724 Regressions found:

`WikiActivityInterpreterTest`, `WikiNodeLocalServiceTest`, `WikiPageSearchTest`, `MBMessageSearchTest`, `DLFileEntrySearchTest`, `DLFileEntrySearchLegacyDDMIndexFieldsTest`, `DocumentLibraryConvertProcessTest`
```
  [exec] com.liferay.wiki.social.test.WikiActivityInterpreterTest > testActivityInterpreter FAILED
     [exec]     java.lang.NoClassDefFoundError: org/apache/poi/ooxml/extractor/ExtractorFactory
     [exec]     	at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:82)
     [exec]     	at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:113)
     [exec]     	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
     [exec]     	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
     [exec]     	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-07/test-1-32/test-portal-acceptance-pullrequest(master)/4649/modules-integration-mysql57-jdk8/3/24/jenkins-console.txt.gz?authuser=0)

`ReportEngineImplTest`
```
com.liferay.portal.reports.engine.console.jasper.internal.test.ReportEngineImplTest > testExportXls FAILED
    java.lang.NoSuchMethodError: org.apache.poi.hssf.usermodel.HSSFFont.getIndex()S
    	at net.sf.jasperreports.engine.export.JRXlsExporter$StyleInfo.computeHash(JRXlsExporter.java:2499)
    	at net.sf.jasperreports.engine.export.JRXlsExporter$StyleInfo.<init>(JRXlsExporter.java:2489)
    	at net.sf.jasperreports.engine.export.JRXlsExporter$StyleInfo.<init>(JRXlsExporter.java:2450)
    	at net.sf.jasperreports.engine.export.JRXlsExporter.getLoadedCellStyle(JRXlsExporter.java:1411)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-07/test-1-32/test-portal-acceptance-pullrequest(master)/4649/modules-integration-mysql57-jdk8/4/2/jenkins-console.txt.gz?authuser=0)

`BatchEngineExportTaskExecutorTest` 
```
  [exec] com.liferay.batch.engine.internal.test.BatchEngineExportTaskExecutorTest > testExportBlogPostingsToXLSFileWithFieldNames FAILED
     [exec]     org.apache.poi.EmptyFileException: The supplied file was empty (zero bytes long)
     [exec]     	at org.apache.poi.util.IOUtils.peekFirstNBytes(IOUtils.java:144)
     [exec]     	at org.apache.poi.poifs.filesystem.FileMagic.valueOf(FileMagic.java:209)
     [exec]     	at org.apache.poi.openxml4j.opc.internal.ZipHelper.verifyZipHeader(ZipHelper.java:143)
     [exec]     	at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipStream(ZipHelper.java:175)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-07/test-1-32/test-portal-acceptance-pullrequest(master)/4649/modules-integration-mysql57-jdk8/0/8/jenkins-console.txt.gz?authuser=0)

`XLSBatchEngineImportTaskItemReaderImplTest`
```
 [exec] com.liferay.batch.engine.internal.reader.XLSBatchEngineImportTaskItemReaderImplTest > testReadInvalidRow FAILED
     [exec]     java.lang.NoClassDefFoundError: org/apache/commons/io/output/UnsynchronizedByteArrayOutputStream
     [exec]         at com.liferay.batch.engine.internal.reader.XLSBatchEngineImportTaskItemReaderImplTest._getContent(XLSBatchEngineImportTaskItemReaderImplTest.java:367)
     [exec]         at com.liferay.batch.engine.internal.reader.XLSBatchEngineImportTaskItemReaderImplTest._getXLSBatchEngineImportTaskItemReader(XLSBatchEngineImportTaskItemReaderImplTest.java:392)
     [exec]         at com.liferay.batch.engine.internal.reader.XLSBatchEngineImportTaskItemReaderImplTest.testReadInvalidRow(XLSBatchEngineImportTaskItemReaderImplTest.java:195)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-07/test-1-32/test-portal-acceptance-pullrequest(master)/4649/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

`TextExtractorTest`
```
 [exec] com.liferay.portal.tika.test.TextExtractorTest > testPpt FAILED
     [exec]     java.lang.NoSuchFieldError: WORKBOOK_DIR_ENTRY_NAMES
     [exec]     	at org.apache.tika.parser.microsoft.POIFSContainerDetector.detect(POIFSContainerDetector.java:214)
     [exec]     	at org.apache.tika.parser.microsoft.POIFSContainerDetector.detect(POIFSContainerDetector.java:489)
     [exec]     	at org.apache.tika.detect.CompositeDetector.detect(CompositeDetector.java:84)
     [exec]     	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:116)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-07/test-1-32/test-portal-acceptance-pullrequest(master)/4649/modules-integration-mysql57-jdk8/3/5/jenkins-console.txt.gz?authuser=0)

`BatchEngineImportTaskExecutorTest`
```
com.liferay.batch.engine.internal.test.BatchEngineImportTaskExecutorTest > testUpdateBlogPostingsFromXLSFile FAILED
    java.lang.AssertionError: expected:<18> but was:<0>
    	at org.junit.Assert.fail(Assert.java:89)
    	at org.junit.Assert.failNotEquals(Assert.java:835)
    	at org.junit.Assert.assertEquals(Assert.java:647)
    	at org.junit.Assert.assertEquals(Assert.java:633)
    	at com.liferay.batch.engine.internal.test.BatchEngineImportTaskExecutorTest._assertUpdatedBlogPostings(BatchEngineImportTaskExecutorTest.java:590)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-07/test-1-32/test-portal-acceptance-pullrequest(master)/4649/modules-integration-mysql57-jdk8/0/8/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
