### PR TITLE
new_remove_usage_of_stream_on_object_rest_impl

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @Kvale1733 , could you help me to check if there is any regression here, please?
Thanks!

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Pull request closed without merging**
