### PR TITLE
backup

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:headless

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
Hey @Kvale1733 , could you please help me see what is wrong here, please?

**Comment by Kvale1733** [comment]
@jeffwu0724 Regressions found

1) No suitable methhod found for filter error
```
  [exec] /opt/dev/projects/github/liferay-portal/modules/apps/headless/headless-delivery/headless-delivery-test/src/testIntegration/java/com/liferay/headless/delivery/resource/v1_0/test/BaseWikiNodeResourceTestCase.java:1582: error: no suitable method found for filter(java.lang.reflect.Field[],(field)->![...]tic())
     [exec] 		List<java.lang.reflect.Field> declaredFields = ListUtil.filter(
     [exec] 		                                                       ^
     [exec]     method com.liferay.portal.kernel.util.ListUtil.<T>filter(java.util.List<? extends T>,java.util.List<T>,java.util.function.Predicate<T>) is not applicable
     [exec]       (cannot infer type-variable(s) T
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.kernel.util.ListUtil.<T>filter(java.util.List<? extends T>,java.util.function.Predicate<T>) is not applicable
     [exec]       (cannot infer type-variable(s) T
     [exec]         (argument mismatch; java.lang.reflect.Field[] cannot be converted to java.util.List<? extends T>))
```
[Full Log](https://testray.liferay.com/reports/production/logs/2023-02/test-1-39/test-portal-acceptance-pullrequest(master)/3098/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

2) Cannot find symbol error
```
 [exec] /opt/dev/projects/github/liferay-portal/modules/apps/analytics/analytics-settings-rest-client/src/main/java/com/liferay/analytics/settings/rest/client/json/BaseJSONParser.java:17: error: package com.liferay.petra.function.transform does not exist
     [exec] import com.liferay.petra.function.transform.TransformUtil;
     [exec]                                            ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/analytics/analytics-settings-rest-client/src/main/java/com/liferay/analytics/settings/rest/client/resource/v1_0/FieldResource.java:23: error: package com.liferay.petra.function.transform does not exist
     [exec] import com.liferay.petra.function.transform.TransformUtil;
     [exec]                                            ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/analytics/analytics-settings-rest-client/src/main/java/com/liferay/analytics/settings/rest/client/serdes/v1_0/ChannelSerDes.java:20: error: package com.liferay.petra.function.transform does not exist
     [exec] import com.liferay.petra.function.transform.TransformUtil;
     [exec]                                            ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/analytics/analytics-settings-rest-client/src/main/java/com/liferay/analytics/settings/rest/client/json/BaseJSONParser.java:206: error: cannot find symbol
     [exec] 		return TransformUtil.transform(
     [exec] 		       ^
     [exec]   symbol:   variable TransformUtil
     [exec]   location: class com.liferay.analytics.settings.rest.client.json.BaseJSONParser<T>
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/analytics/analytics-settings-rest-client/src/main/java/com/liferay/analytics/settings/rest/client/json/BaseJSONParser.java:211: error: cannot 
```
[Full Log](https://testray.liferay.com/reports/production/logs/2023-02/test-1-27/test-portal-acceptance-pullrequest(master)/6991/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
Hey @zhangyan0701 , could you please help me see what is wrong here?
Thanks!

**Comment by Kvale1733** [comment]
@jeffwu0724 There are a lot of failing tests, but all seem to have the same root cause. 
 java.lang.IllegalArgumentException: Unsupported field name actions
 Here's an example

com.liferay.headless.admin.workflow.resource.v1_0.test.WorkflowTaskTransitionsResourceTest

```
[exec] com.liferay.headless.admin.user.resource.v1_0.test.SegmentResourceTest > testGetSiteSegmentsPage FAILED
     [exec]     java.lang.IllegalArgumentException: Unsupported field name actions
     [exec]     	at com.liferay.headless.admin.user.client.problem.Problem$ProblemJSONParser.setField(Problem.java:178)
     [exec]     	at com.liferay.headless.admin.user.client.problem.Problem$ProblemJSONParser.setField(Problem.java:140)
     [exec]     	at com.liferay.headless.admin.user.client.json.BaseJSONParser.parseToDTO(BaseJSONParser.java:91)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-02/test-1-38/test-portal-acceptance-pullrequest(master)/6466/modules-integration-mysql57-jdk8/0/20/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:stop

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 same issue as before causing many tests to fail

```
  [exec] com.liferay.headless.delivery.resource.v1_0.test.MessageBoardSectionResourceTest > testGetMessageBoardSectionMessageBoardSectionsPage FAILED
     [exec]     java.lang.IllegalArgumentException: Unsupported field name actions
     [exec]     	at com.liferay.headless.delivery.client.problem.Problem$ProblemJSONParser.setField(Problem.java:178)
     [exec]     	at com.liferay.headless.delivery.client.problem.Problem$ProblemJSONParser.setField(Problem.java:140)
     [exec]     	at com.liferay.headless.delivery.client.json.BaseJSONParser.parseToDTO(BaseJSONParser.java:91)
     [exec]     	at com.liferay.headless.delivery.client.problem.Problem.toDTO(Problem.java:33)
     [exec]     	at 
```
[Log](https://testray.liferay.com/reports/production/logs/2023-02/test-1-37/test-portal-acceptance-pullrequest(master)/9263/modules-integration-mysql57-jdk8/0/21/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
