### PR TITLE
LPS-149258

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by jeffwu0724** [comment]
ci:stop

**Comment by jeffwu0724** [comment]
https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1890548523

**Comment by catarineaguiar** [comment]
Hey @jeffwu0724, some tests were aborted, but I could find this regressions:

SF issue:
```
[java] java.lang.Exception: Found 9 formatting issues:
     [java] 1: ./modules/dxp/apps/document-library-opener/document-library-opener-onedrive-web/bnd.bnd expected:<...
     [java] Import-Package:\
     [java] 	![android.os,\
     [java] 	\
     [java] 	!android.util,\
     [java] 	\
     [java] 	!com.github.luben.*,\
     [java] 	\
     [java] 	!com.google.common.util.concurrent.*,\
     [java] 	!com.google.errorprone.annotations.*,\
     [java] 	\
     [java] 	!com.graphbuilder.*,\
     [java] 	\
     [java] 	!com.microsoft.schemas.office.powerpoint.*,\
     [java] 	!com.microsoft.schemas.office.word.*,\
     [java] 	\
     [java] 	!com.sun.javadoc.*,\
     [java] 	!com.sun.tools.javadoc.*,\
     [java] 	\
     [java] 	!javax.annotation.meta.*,\
     [java] 	\
     [java] 	!junit.framework,\
     [java] 	\
     [java] 	!net.sf.saxon.*,\
     [java] 	\
     [java] 	!org.apache.batik.anim.dom.*,\
     [java] 	!org.apache.batik.bridge.*,\
     [java] 	!org.apache.batik.ext.awt.*,\
     [java] 	!org.apache.batik.gvt.*,\
     [java] 	!org.apache.batik.util.*,\
     [java] 	!org.apache.commons.math3.*,\
     [java] 	!org.apache.http.*,\
     [java] 	!org.apache.jcp.xml.dsig.internal.dom.*,\
     [java] 	!org.apache.poi.hsmf.*,\
     [java] 	!org.apache.poi.hwpf.extractor.*,\
     [java] 	!org.apache.poi.xssf.usermodel],\
     [java] 	!org.apache.tool...> but was:<...
     [java] Import-Package:\
     [java] 	![org.apache.poi.xssf.usermodel,\
     [java] 	!android.os,\
     [java] 	\
     [java] 	!android.util,\
     [java] 	\
     [java] 	!com.github.luben.*,\
     [java] 	\
     [java] 	!com.google.common.util.concurrent.*,\
     [java] 	!com.google.errorprone.annotations.*,\
     [java] 	\
     [java] 	!com.graphbuilder.*,\
     [java] 	\
     [java] 	!com.microsoft.schemas.office.powerpoint.*,\
     [java] 	!com.microsoft.schemas.office.word.*,\
     [java] 	\
     [java] 	!com.sun.javadoc.*,\
     [java] 	!com.sun.tools.javadoc.*,\
     [java] 	\
     [java] 	!javax.annotation.meta.*,\
     [java] 	\
     [java] 	!junit.framework,\
     [java] 	\
     [java] 	!net.sf.saxon.*,\
     [java] 	\
     [java] 	!org.apache.batik.anim.dom.*,\
     [java] 	!org.apache.batik.bridge.*,\
     [java] 	!org.apache.batik.ext.awt.*,\
     [java] 	!org.apache.batik.gvt.*,\
     [java] 	!org.apache.batik.util.*,\
     [java] 	!org.apache.commons.math3.*,\
     [java] 	!org.apache.http.*,\
     [java] 	!org.apache.jcp.xml.dsig.internal.dom.*,\
     [java] 	!org.apache.poi.hsmf.*,\
     [java] 	!org.apache.poi.hwpf.extractor.*],\
     [java] 	!org.apache.tool...>
     [java] 2: ./modules/dxp/apps/portal-reports-engine-console/portal-reports-engine-console-jasper/bnd.bnd expected:<...
     [java] Import-Package:\
     [java] 	![antlr.*,\
     [java] 	\
     [java] 	!bsh,\
     [java] 	\
     [java] 	!com.adobe.internal.xmp.*,\
     [java] 	\
     [java] 	!com.apple.mrj.*,\
     [java] 	\
     [java] 	!com.drew.*,\
     [java] 	\
     [java] 	!com.fasterxml.jackson.*,\
     [java] 	\
     [java] 	!com.keypoint.*,\
     [java] 	\
     [java] 	!com.lowagie.toolbox.*,\
     [java] 	\
     [java] 	!com.thoughtworks.*,\
     [java] 	\
     [java] 	!groovyjarjarasm.asm.tree.analysis.*,\
     [java] 	\
     [java] 	!javax.accessibility.*,\
     [java] 	\
     [java] 	!javax.crypto.*,\
     [java] 	\
     [java] 	!javax.imageio.*,\
     [java] 	\
     [java] 	!javax.print.*,\
     [java] 	\
     [java] 	!javax.rmi.*,\
     [java] 	\
     [java] 	!javax.swing.*,\
     [java] 	\
     [java] 	!jline.*,\
     [java] 	\
     [java] 	!junit.*,\
     [java] 	\
     [java] 	!mondrian.*,\
     [java] 	\
     [java] 	!net.sourceforge.barbecue.*,\
     [java] 	\
     [java] 	!org.apache.bcel.*,\
     [java] 	!org.apache.bsf.*,\
     [java] 	!org.apache.commons.cli.*,\
     [java] 	!org.apache.commons.javaflow.*,\
     [java] 	!org.apache.commons.jci.*,\
     [java] 	!org.apache.ivy.*,\
     [java] 	!org.apache.log.*,\
     [java] 	!org.apache.oro.*,\
     [java] 	!org.apache.poi.hdgf.*,\
     [java] 	!org.apache.poi.hpbf.*,\
     [java] 	!org.apache.poi.hslf.*,\
     [java] 	!org.apache.poi.hsmf.*,\
     [java] 	!org.apache.poi.hssf.*,\
     [java] 	!org.apache.poi.hwpf.*,\
     [java] 	!org.apache.poi.poifs.*,\
     [java] 	!org.apache.poi.sl.*,\
     [java] 	!org.apache.poi.ss.*,\
     [java] 	!org.apache.poi.xssf.*,\
     [java] 	!org.apache.tools.*,\
     [java] 	!org.apache.velocity.*,\
     [java] 	!org.apache.xerces.impl.xpath.regex.*,\
     [java] 	!org.apache.xml.resolver.*,\
     [java] 	!org.apache.xmlbeans.*,\
     [java] 	!org.apache.xpath.*,\
     [java] 	\
     [java] 	!org.dom4j.*,\
     [java] 	\
     [java] 	!org.eclipse.*,\
     [java] 	\
     [java] 	!org.exolab.castor.*,\
     [java] 	\
     [java] 	!org.fusesource.*,\
     [java] 	\
     [java] 	!org.hibernate.*,\
     [java] 	\
     [java] 	!org.junit.*,\
     [java] 	\
     [java] 	!org.kohsuke.groovy.sandbox],\
     [java] 	\
     [java] 	!org.krysalis...> but was:<...
     [java] Import-Package:\
     [java] 	![com.adobe.internal.xmp.*,\
     [java] 	!com.drew.*,\
     [java] 	!org.kohsuke.groovy.sandbox,\
     [java] 	!antlr.*,\
     [java] 	\
     [java] 	!bsh,\
     [java] 	\
     [java] 	!com.apple.mrj.*,\
     [java] 	\
     [java] 	!com.fasterxml.jackson.*,\
     [java] 	\
     [java] 	!com.keypoint.*,\
     [java] 	\
     [java] 	!com.lowagie.toolbox.*,\
     [java] 	\
     [java] 	!com.thoughtworks.*,\
     [java] 	\
     [java] 	!groovyjarjarasm.asm.tree.analysis.*,\
     [java] 	\
     [java] 	!javax.accessibility.*,\
     [java] 	\
     [java] 	!javax.crypto.*,\
     [java] 	\
     [java] 	!javax.imageio.*,\
     [java] 	\
     [java] 	!javax.print.*,\
     [java] 	\
     [java] 	!javax.rmi.*,\
     [java] 	\
     [java] 	!javax.swing.*,\
     [java] 	\
     [java] 	!jline.*,\
     [java] 	\
     [java] 	!junit.*,\
     [java] 	\
     [java] 	!mondrian.*,\
     [java] 	\
     [java] 	!net.sourceforge.barbecue.*,\
     [java] 	\
     [java] 	!org.apache.bcel.*,\
     [java] 	!org.apache.bsf.*,\
     [java] 	!org.apache.commons.cli.*,\
     [java] 	!org.apache.commons.javaflow.*,\
     [java] 	!org.apache.commons.jci.*,\
     [java] 	!org.apache.ivy.*,\
     [java] 	!org.apache.log.*,\
     [java] 	!org.apache.oro.*,\
     [java] 	!org.apache.poi.hdgf.*,\
     [java] 	!org.apache.poi.hpbf.*,\
     [java] 	!org.apache.poi.hslf.*,\
     [java] 	!org.apache.poi.hsmf.*,\
     [java] 	!org.apache.poi.hssf.*,\
     [java] 	!org.apache.poi.hwpf.*,\
     [java] 	!org.apache.poi.poifs.*,\
     [java] 	!org.apache.poi.sl.*,\
     [java] 	!org.apache.poi.ss.*,\
     [java] 	!org.apache.poi.xssf.*,\
     [java] 	!org.apache.tools.*,\
     [java] 	!org.apache.velocity.*,\
     [java] 	!org.apache.xerces.impl.xpath.regex.*,\
     [java] 	!org.apache.xml.resolver.*,\
     [java] 	!org.apache.xmlbeans.*,\
     [java] 	!org.apache.xpath.*,\
     [java] 	\
     [java] 	!org.dom4j.*,\
     [java] 	\
     [java] 	!org.eclipse.*,\
     [java] 	\
     [java] 	!org.exolab.castor.*,\
     [java] 	\
     [java] 	!org.fusesource.*,\
     [java] 	\
     [java] 	!org.hibernate.*,\
     [java] 	\
     [java] 	!org.junit.*],\
     [java] 	\
     [java] 	!org.krysalis...>
     [java] 3: ./modules/dxp/apps/portal-reports-engine-console/portal-reports-engine-console-jasper-test/bnd.bnd expected:<...
     [java] Import-Package:\
     [java] 	![com.zaxxer.sparsebits.*,\
     [java] 	\
     [java] 	!org.apache.poi.common.usermodel],\
     [java] 	\
     [java] 	!org.bouncyca...> but was:<...
     [java] Import-Package:\
     [java] 	![org.apache.poi.common.usermodel,\
     [java] 	!com.zaxxer.sparsebits.*],\
     [java] 	\
     [java] 	!org.bouncyca...>
     [java] 4: ./modules/apps/shared-dependencies/shared-dependencies-poi/bnd.bnd expected:<...
     [java] Import-Package:\
     [java] 	![com.github.javaparser.*,\
     [java] 	\
     [java] 	!com.graphbuilder.curve,\
     [java] 	!com.graphbuilder.geom,\
     [java] 	\
     [java] 	!com.microsoft.schemas.office.powerpoint,\
     [java] 	\
     [java] 	!com.sun.org.apache.xml.internal.resolver.*,\
     [java] 	\
     [java] 	!com.zaxxer.sparsebits,\
     [java] 	\
     [java] 	!de.rototor.pdfbox.graphics2d,\
     [java] 	\
     [java] 	!net.sf.saxon.*,\
     [java] 	\
     [java] 	!org.apache.batik.anim.dom,\
     [java] 	!org.apache.batik.bridge,\
     [java] 	!org.apache.batik.dom,\
     [java] 	!org.apache.batik.ext.awt,\
     [java] 	!org.apache.batik.ext.awt.image.renderable,\
     [java] 	!org.apache.batik.gvt,\
     [java] 	!org.apache.batik.parser,\
     [java] 	!org.apache.batik.svggen,\
     [java] 	!org.apache.batik.util,\
     [java] 	!org.apache.commons.collections4,\
     [java] 	!org.apache.commons.collections4.bidimap,\
     [java] 	!org.apache.commons.collections4.iterators,\
     [java] 	!org.apache.commons.collections4.multimap,\
     [java] 	!org.apache.commons.math3.distribution,\
     [java] 	!org.apache.commons.math3.exception,\
     [java] 	!org.apache.commons.math3.linear,\
     [java] 	!org.apache.commons.math3.random,\
     [java] 	!org.apache.commons.math3.special,\
     [java] 	!org.apache.commons.math3.stat.descriptive.moment,\
     [java] 	!org.apache.commons.math3.stat.regression,\
     [java] 	!org.apache.jcp.xml.dsig.internal.dom,\
     [java] 	!org.apache.maven.*,\
     [java] 	!org.apache.tools.ant.*],\
     [java] 	!org.apache.xmlb...> but was:<...
     [java] Import-Package:\
     [java] 	![org.apache.tools.ant.*,\
     [java] 	!org.apache.maven.*,\
     [java] 	!net.sf.saxon.*,\
     [java] 	!com.sun.org.apache.xml.internal.resolver.*,\
     [java] 	!com.github.javaparser.*,\
     [java] 	!com.graphbuilder.curve,\
     [java] 	!com.graphbuilder.geom,\
     [java] 	\
     [java] 	!com.microsoft.schemas.office.powerpoint,\
     [java] 	\
     [java] 	!com.zaxxer.sparsebits,\
     [java] 	\
     [java] 	!de.rototor.pdfbox.graphics2d,\
     [java] 	\
     [java] 	!org.apache.batik.anim.dom,\
     [java] 	!org.apache.batik.bridge,\
     [java] 	!org.apache.batik.dom,\
     [java] 	!org.apache.batik.ext.awt,\
     [java] 	!org.apache.batik.ext.awt.image.renderable,\
     [java] 	!org.apache.batik.gvt,\
     [java] 	!org.apache.batik.parser,\
     [java] 	!org.apache.batik.svggen,\
     [java] 	!org.apache.batik.util,\
     [java] 	!org.apache.commons.collections4,\
     [java] 	!org.apache.commons.collections4.bidimap,\
     [java] 	!org.apache.commons.collections4.iterators,\
     [java] 	!org.apache.commons.collections4.multimap,\
     [java] 	!org.apache.commons.math3.distribution,\
     [java] 	!org.apache.commons.math3.exception,\
     [java] 	!org.apache.commons.math3.linear,\
     [java] 	!org.apache.commons.math3.random,\
     [java] 	!org.apache.commons.math3.special,\
     [java] 	!org.apache.commons.math3.stat.descriptive.moment,\
     [java] 	!org.apache.commons.math3.stat.regression,\
     [java] 	!org.apache.jcp.xml.dsig.internal.dom],\
     [java] 	!org.apache.xmlb...>
     [java] 5: ./modules/apps/dynamic-data-lists/dynamic-data-lists-service/bnd.bnd expected:<...
     [java] Import-Package:\
     [java] 	![com.graphbuilder.*,\
     [java] 	\
     [java] 	!org.apache.poi.hssf.usermodel,]\
     [java] 	!org.apache.tools...> but was:<...
     [java] Import-Package:\
     [java] 	![org.apache.poi.hssf.usermodel,\
     [java] 	!com.graphbuilder.*,\
     [java] 	]\
     [java] 	!org.apache.tools...>
     [java] 6: ./modules/apps/content-dashboard/content-dashboard-web/bnd.bnd expected:<...
     [java] Import-Package:\
     [java] 	![com.graphbuilder.*,\
     [java] 	\
     [java] 	!org.apache.poi.hssf.usermodel,]\
     [java] 	!org.apache.tools...> but was:<...
     [java] Import-Package:\
     [java] 	![org.apache.poi.hssf.usermodel,\
     [java] 	!com.graphbuilder.*,\
     [java] 	]\
     [java] 	!org.apache.tools...>
     [java] 7: ./modules/apps/commerce/commerce-report-impl/bnd.bnd expected:<...
     [java] Import-Package:\
     [java] 	![antlr.*,\
     [java] 	\
     [java] 	!bsh,\
     [java] 	\
     [java] 	!com.apple.mrj.*,\
     [java] 	\
     [java] 	!com.fasterxml.jackson.*,\
     [java] 	\
     [java] 	!com.github.javaparser,\
     [java] 	\
     [java] 	!com.keypoint.*,\
     [java] 	\
     [java] 	!com.lowagie.toolbox.*,\
     [java] 	\
     [java] 	!com.thoughtworks.*,\
     [java] 	\
     [java] 	!groovyjarjarasm.asm.tree.analysis.*,\
     [java] 	\
     [java] 	!javax.accessibility.*,\
     [java] 	\
     [java] 	!javax.crypto.*,\
     [java] 	\
     [java] 	!javax.imageio.*,\
     [java] 	\
     [java] 	!javax.print.*,\
     [java] 	\
     [java] 	!javax.rmi.*,\
     [java] 	\
     [java] 	!javax.swing.*,\
     [java] 	\
     [java] 	!jline.*,\
     [java] 	\
     [java] 	!junit.*,\
     [java] 	\
     [java] 	!mondrian.*,\
     [java] 	\
     [java] 	!net.sourceforge.barbecue.*,\
     [java] 	\
     [java] 	!org.apache.bcel.*,\
     [java] 	!org.apache.bsf.*,\
     [java] 	!org.apache.commons.cli.*,\
     [java] 	!org.apache.commons.javaflow.*,\
     [java] 	!org.apache.commons.jci.*,\
     [java] 	!org.apache.ivy.*,\
     [java] 	!org.apache.log.*,\
     [java] 	!org.apache.oro.*,\
     [java] 	!org.apache.poi.common.usermodel],\
     [java] 	!org.apache.poi....> but was:<...
     [java] Import-Package:\
     [java] 	![com.github.javaparser,\
     [java] 	!org.apache.poi.common.usermodel,\
     [java] 	!antlr.*,\
     [java] 	\
     [java] 	!bsh,\
     [java] 	\
     [java] 	!com.apple.mrj.*,\
     [java] 	\
     [java] 	!com.fasterxml.jackson.*,\
     [java] 	\
     [java] 	!com.keypoint.*,\
     [java] 	\
     [java] 	!com.lowagie.toolbox.*,\
     [java] 	\
     [java] 	!com.thoughtworks.*,\
     [java] 	\
     [java] 	!groovyjarjarasm.asm.tree.analysis.*,\
     [java] 	\
     [java] 	!javax.accessibility.*,\
     [java] 	\
     [java] 	!javax.crypto.*,\
     [java] 	\
     [java] 	!javax.imageio.*,\
     [java] 	\
     [java] 	!javax.print.*,\
     [java] 	\
     [java] 	!javax.rmi.*,\
     [java] 	\
     [java] 	!javax.swing.*,\
     [java] 	\
     [java] 	!jline.*,\
     [java] 	\
     [java] 	!junit.*,\
     [java] 	\
     [java] 	!mondrian.*,\
     [java] 	\
     [java] 	!net.sourceforge.barbecue.*,\
     [java] 	\
     [java] 	!org.apache.bcel.*,\
     [java] 	!org.apache.bsf.*,\
     [java] 	!org.apache.commons.cli.*,\
     [java] 	!org.apache.commons.javaflow.*,\
     [java] 	!org.apache.commons.jci.*,\
     [java] 	!org.apache.ivy.*,\
     [java] 	!org.apache.log.*,\
     [java] 	!org.apache.oro.*],\
     [java] 	!org.apache.poi....>
     [java] 8: ./modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/bnd.bnd expected:<...
     [java] Import-Package:\
     [java] 	![com.fasterxml.jackson.*,\
     [java] 	\
     [java] 	!com.google.gson.*,\
     [java] 	\
     [java] 	!com.graphbuilder.*,\
     [java] 	\
     [java] 	!org.apache.poi.hssf.usermodel,]\
     [java] 	!org.apache.tapes...> but was:<...
     [java] Import-Package:\
     [java] 	![org.apache.poi.hssf.usermodel,\
     [java] 	!com.fasterxml.jackson.*,\
     [java] 	\
     [java] 	!com.google.gson.*,\
     [java] 	\
     [java] 	!com.graphbuilder.*,\
     [java] 	]\
     [java] 	!org.apache.tapes...>
     [java] 9: ./modules/apps/shared-dependencies/shared-dependencies-poi/build.gradle expected:<...pileInclude group: "[com.zaxxer", name: "SparseBitSet", version: "1.2"
     [java] 	compileInclude group: "org.apache.commons", name: "commons-collections4", version: "4.4"
     [java] 	compileInclude group: "org.apache.poi", name: "poi", version: "5.2.2"
     [java] 	compileInclude group: "org.apache.poi", name: "poi-ooxml", version: "5.2.2"
     [java] 	compileInclude group: "org.apache.poi", name: "poi-ooxml-full", version: "5.2.2]"
     [java] 	compileInclude gr...> but was:<...pileInclude group: "[org.apache.poi", name: "poi", version: "5.2.2"
     [java] 	compileInclude group: "org.apache.poi", name: "poi-ooxml", version: "5.2.2"
     [java] 	compileInclude group: "org.apache.poi", name: "poi-ooxml-full", version: "5.2.2"
     [java] 	compileInclude group: "com.zaxxer", name: "SparseBitSet", version: "1.2"
     [java] 	compileInclude group: "org.apache.commons", name: "commons-collections4", version: "4.4]"
     [java] 	compileInclude gr...>
     [java] 
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-06/test-1-39/test-portal-acceptance-pullrequest(master)/330/source-format-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar , may I ask besides SF issues, if there are any other regressions at this time, please? Would you mind also help me to check again when the newer acceptance test report it out, please?  :)

**Comment by catarineaguiar** [comment]
the other regression was:

Steps to reproduce:

1. In menu > go to configurations
2. reports admin > definitions
3. click to add a new definition
4. add a report in this definition you created

in the logs appear this error:
```
ERROR [liferay/report_request-4][ReportRequestMessageListener:68] Unable to generate report
com.liferay.portal.kernel.log.LogSanitizerException: com.liferay.portal.reports.engine.ReportGenerationException: Unable to execute report: net.sf.jasperreports.engine.JRException: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence._	at net.sf.jasperreports.engine.xml.JRXmlLoader.loadXML(JRXmlLoader.java:273)_	at net.sf.jasperreports.engine.xml.JRXmlLoader.loadXML(JRXmlLoader.java:256)_	at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:245)_	at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:223)_	at net.sf.jasperreports.engine.JasperCompileManager.compile(JasperCompileManager.java:342)_	at net.sf.jasperreports.engine.JasperCompileManager.compileReport(JasperCompileManager.java:609)_	at com.liferay.portal.reports.engine.console.jasper.internal.compiler.DefaultReportCompiler.compile(DefaultReportCompiler.java:52)_	at com.liferay.portal.reports.engine.console.jasper.internal.compiler.DefaultReportCompiler.compile(DefaultReportCompiler.java:36)_	at com.liferay.portal.reports.engine.console.jasper.internal.ReportEngineImpl.execute(ReportEngineImpl.java:98)_	at com.liferay.portal.reports.engine.messaging.ReportRequestMessageListener.doReceive(ReportRequestMessageListener.java:65)_	at com.liferay.portal.kernel.messaging.BaseMessageListener.doReceive(BaseMessageListener.java:48)_	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:34)_	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)_	at com.liferay.portal.messaging.internal.ParallelDestination$1.run(ParallelDestination.java:56)_	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)_	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)_	at java.lang.Thread.run(Thread.java:748)_Caused by: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence._	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF8Reader.java:701)_	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:567)_	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1895)_	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.arrangeCapacity(XMLEntityScanner.java:1761)_	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipString(XMLEntityScanner.java:1799)_	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:156)_	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:806)_	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)_	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)_	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)_	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)_	at org.apache.commons.digester.Digester.parse(Digester.java:1892)_	at net.sf.jasperreports.engine.xml.JRXmlLoader.loadXML(JRXmlLoader.java:269)_	... 16 more_ [Sanitized]
	at com.liferay.portal.reports.engine.console.jasper.internal.ReportEngineImpl.execute(ReportEngineImpl.java:121) ~[?:?]
	at com.liferay.portal.reports.engine.messaging.ReportRequestMessageListener.doReceive(ReportRequestMessageListener.java:65) [bundleFile:?]
	at com.liferay.portal.kernel.messaging.BaseMessageListener.doReceive(BaseMessageListener.java:48) [portal-kernel.jar:?]
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:34) [portal-kernel.jar:?]
	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74) [portal-kernel.jar:?]
	at com.liferay.portal.messaging.internal.ParallelDestination$1.run(ParallelDestination.java:56) [bundleFile:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
```

**Comment by catarineaguiar** [comment]
Sure, I'll re-analyze the new results.

**Pull request closed without merging**
