### PR TITLE
remove_stream_in_portal_search

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar , could you please help me check what goes wrong, please?

**Comment by catarineaguiar** [comment]
@jeffwu0724 I didn't find any unique failure

**Comment by jeffwu0724** [comment]
Thanks! @catarineaguiar

**Pull request closed without merging**
