### PR TITLE
LPS-149258

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar, could you please help me look at the test result when it is ready?
Thanks for your help!

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 Regression found

1. Many Integration tests were aborted and functional tests failed. They all have unsatisfied references in the logs
`Bundle {id: 114, name: com.liferay.portal.workflow.kaleo.runtime.scripting.impl, version: 5.0.10}
[beanshell] 	Declarative Service {id: 109, name: com.liferay.portal.workflow.kaleo.runtime.scripting.internal.action.ScriptActionExecutor, unsatisfied references: 
[beanshell] 		{name: _kaleoScriptingEvaluator, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 1087, name: com.liferay.portal.workflow.kaleo.runtime.scripting.internal.notification.recipient.script.DRLNotificationRecipientEvaluator, unsatisfied references: 
[beanshell] 		{name: _rulesContextBuilder, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 113, name: com.liferay.portal.workflow.kaleo.runtime.scripting.internal.notification.recipient.script.ScriptingNotificationRecipientEvaluator, unsatisfied references: 
[beanshell] 		{name: _kaleoScriptingEvaluator, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 1085, name: com.liferay.portal.workflow.kaleo.runtime.scripting.internal.action.DRLActionExecutor, unsatisfied references: 
[beanshell] 		{name: _rulesContextBuilder, target: null}` [Testray Example](https://testray.liferay.com/home/-/testray/case_results/1983244484?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1983176106%26testrayRunId%3D1983176132%26cur%3D3%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26resetCur%3Dfalse)

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @Kvale1733 , can you help me check the result when it is ready, please?
Thanks a lot!

**Pull request closed without merging**
