### PR TITLE
Remove deprecated for portal kernel part six

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi,

I have removed deprecated for 
"ModelResourcePermissionHelper.java"
"ThreadLocalCompanyProvider" and "CompanyProviderWrapper"
"InvokerFilter.java"
"portal-kernel/src/com/liferay/portal/kernel/servlet/taglib/aui"
"SocialActivityManagerUtil.java"
"portal-kernel/src/com/liferay/portal/kernel/template"
"ThemeDisplay.java"
"renderActions()"
"isImageDefaultUseInitials()"
Thanks for checking. Also see https://github.com/jeffwu0724/liferay-portal/pull/44

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by kyle-miho** [comment]
@jeffwu0724 failures are unrelated

**Pull request closed without merging**
