### PR TITLE
move_upload_to_modues_test_3_31

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:stop

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @Kvale1733 , could you please help me check the test result when it is ready?
Thanks!

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar , could you please help me check this test result?
Thanks!

**Comment by catarineaguiar** [comment]
@jeffwu0724 regressions found:

warn on startup
```
    [junit] 2023-04-03 18:08:33.243 WARN  [ServerService Thread Pool -- 77][SystemCheckOSGiCommands:154] Declarative Service Unsatisfied Component Checker check result: 
    [junit] Bundle {id: 638, name: com.liferay.template.web, version: 1.0.57}
    [junit] 	Declarative Service {id: 8053, name: com.liferay.template.web.internal.portlet.action.UpdateTemplateEntryMVCActionCommand, unsatisfied references: 
    [junit] 		{name: _uploadPortletRequestFactory, target: null}
    [junit] 	}
    [junit] Bundle {id: 1015, name: com.liferay.journal.web, version: 5.0.131}
    [junit] 	Declarative Service {id: 9860, name: com.liferay.journal.web.internal.portlet.action.ImportDataDefinitionMVCActionCommand, unsatisfied references: 
    [junit] 		{name: _uploadPortletRequestFactory, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 9859, name: com.liferay.journal.web.internal.portlet.action.ImportAndOverrideDataDefinitionMVCActionCommand, unsatisfied references: 
    [junit] 		{name: _uploadPortletRequestFactory, target: null}
    [junit] 	}
    [junit] Bundle {id: 1057, name: com.liferay.object.web, version: 1.0.158}
    [junit] 	Declarative Service {id: 10065, name: com.liferay.object.web.internal.object.definitions.portlet.action.ImportObjectDefinitionMVCActionCommand, unsatisfied references: 
    [junit] 		{name: _uploadPortletRequestFactory, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 10029, name: com.liferay.object.web.internal.list.type.portlet.action.ImportListTypeDefinitionMVCActionCommand, unsatisfied references: 
    [junit] 		{name: _uploadPortletRequestFactory, target: null}
    [junit] 	}
    [junit] 2023-04-03 18:08:33.243 INFO  [ServerService Thread Pool -- 77][SystemCheckOSGiCommands:131] Running "Missing Component Scanner". You can run this by itself with command "ds:missing" in gogo shell.
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-04/test-1-33/test-portal-acceptance-pullrequest(master)/3134/functional-smoke-wildfly180-mariadb106-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.template.web.internal.portlet.action.test.UpdateTemplateEntryMVCActionCommandTest > testUpdateTemplateEntry FAILED
     [exec]     java.lang.IllegalStateException: Timed out while waiting for service com.liferay.portal.kernel.portlet.bridges.mvc.MVCActionCommand mvc.command.name=/template/update_template_entry
     [exec]     	at com.liferay.portal.test.rule.InjectTestBag._getServiceReference(InjectTestBag.java:199)
     [exec]     	at com.liferay.portal.test.rule.InjectTestBag.injectFields(InjectTestBag.java:78)
     [exec]     	at com.liferay.portal.test.rule.InjectTestRule.beforeMethod(InjectTestRule.java:61)
     [exec]     	at com.liferay.portal.test.rule.InjectTestRule.beforeMethod(InjectTestRule.java:24)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:94)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-04/test-1-33/test-portal-acceptance-pullrequest(master)/3134/modules-integration-mysql57-jdk8/4/3/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:stop

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Pull request closed without merging**
