### PR TITLE
LPS-187713 move_portal_upload_to_modules_from_impl_and_kernel_712

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar ,

Could you please help me check if this PR has any regression?
Thanks!

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions were found

**Comment by catarineaguiar** [comment]
you can run ci:test:object if need

**Pull request closed without merging**
