### PR TITLE
LPS-138374 move xmpcore to shared-dependencies

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-138374.
i tried to move xmpcore to shared-dependencies.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
Hey @Kvale1733, could you please help me check the test result when it is ready, please?
Thanks!

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by Kvale1733** [comment]
@jeffwu0724 Yeah you are right. There are more results now for those tests and its reproducible at head. So there were no regressions in https://github.com/liferay-core-infra/liferay-portal/pull/2601#issuecomment-1334601076 then.

**Comment by jeffwu0724** [comment]
ci:help

**Pull request closed without merging**
