### PR TITLE
test_backup2

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 Same unsupported field name actions error. Affects a lot of integration tests. Mostly headless tests. 
Example:

com.liferay.headless.admin.user.resource.v1_0.test.PostalAddressResourceTest
```
java.lang.IllegalArgumentException: Unsupported field name actions
		at com.liferay.headless.admin.user.client.problem.Problem$ProblemJSONParser.setField(Problem.java:178)
		at com.liferay.headless.admin.user.client.problem.Problem$ProblemJSONParser.setField(Problem.java:140)
		at com.liferay.headless.admin.user.client.json.BaseJSONParser.parseToDTO(BaseJSONParser.java:91)
		at com.liferay.headless.admin.user.client.problem.Problem.toDTO(Problem.java:33)
		at com.liferay.headless.admin.user.client.resource.v1_0.PostalAddressResource$PostalAddressResourceImpl.getAccountPostalAddressesPage(PostalAddressResource.java:191)
		at com.liferay.headless.admin.user.resource.v1_0.test.BasePostalAddressResourceTestCase.testGetAccountPostalAddressesPage(BasePostalAddressResourceTestCase.java:216)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-02/test-1-33/test-portal-acceptance-pullrequest(master)/2865/modules-integration-mysql57-jdk8/0/20/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
@jeffwu0724 I only see this in the your PRs with these changes. Didn't find it in that other PR you asked me about.

**Comment by jeffwu0724** [comment]
@Kvale1733 , thanks for confirming! I think I know what is the issue now

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
@Kvale1733 , is there still any regression in this PR, please?

**Comment by Kvale1733** [comment]
ci:test:bundle

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Pull request closed without merging**
