### PR TITLE
remove_use_of_portal_impl_using_getProps

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:help

**Comment by jeffwu0724** [comment]
ci:test:lpkg

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:stop

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hi @Kvale1733,

Can you help me look at the test result, please?
Thanks for your help!

**Comment by Kvale1733** [comment]
@jeffwu0724 Rerunning relevant, there is a high number of tests that failed prior to starting.

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 

Regressions found:

1.There are several integration tests which all seem to be failing with the same error:
`java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [META-INF/ext-model-hints.xml]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.`

` 2022-09-12 16:16:52.933 ERROR [Portal Spring Init Thread][ContextLoader:225] Context initialization failed
[beanshell] org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.portal.kernel.security.permission.ResourceActions' defined in class path resource [META-INF/security-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.portal.kernel.service.PortletLocalService' defined in class path resource [META-INF/portal-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.portal.kernel.service.CompanyLocalService' defined in class path resource [META-INF/portal-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.portal.kernel.service.persistence.CompanyInfoPersistence' defined in class path resource [META-INF/portal-spring.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.liferay.portal.service.persistence.impl.CompanyInfoPersistenceImpl]: Constructor threw exception; nested exception is java.lang.ExceptionInInitializerError`Example [Testray](https://testray.liferay.com/home/-/testray/case_results/1974307921?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1974306296%26testrayRunId%3D1974307729%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

2. All of the PortalSmokeUpgrade tests seem to be failing when upgrading a legacy database with the upgrade tool
`Exception in thread "main" java.lang.reflect.InvocationTargetException
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:54)
     [java] Caused by: java.lang.ExceptionInInitializerError
     [java] 	at com.liferay.portal.lpkg.deployer.internal.DefaultLPKGDeployer._activate(DefaultLPKGDeployer.java:334)
     [java] 	at com.liferay.portal.lpkg.deployer.internal.DefaultLPKGDeployer.activate(DefaultLPKGDeployer.java:270)`
     
'Caused by: java.lang.NullPointerException
     [java] 	at com.liferay.portal.lpkg.deployer.internal.DefaultLPKGDeployer.getPropsValue(DefaultLPKGDeployer.java:231)
     [java] 	at com.liferay.portal.lpkg.deployer.internal.LPKGBundleTrackerCustomizer.<clinit>(LPKGBundleTrackerCustomizer.java:928) [Testray](https://testray.liferay.com/home/-/testray/case_results/1974307768?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1974306296%26testrayRunId%3D1974307729%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Pull request closed without merging**
