### PR TITLE
update_xmlbeans_3.1.0

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @Kvale1733 , could you please help me to check the result when you have time?

Thanks!
Jeff

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 Regression in

com.liferay.batch.engine.internal.test.BatchEngineExportTaskExecutorTest
com.liferay.batch.engine.internal.test.BatchEngineImportTaskExecutorTest

```
 com.liferay.batch.engine.internal.test.BatchEngineExportTaskExecutorTest > testExportBlogPostingsToXLSFileWithFieldNames STARTED
[beanshell] 2022-10-08 02:38:34.199 ERROR [com.liferay.batch.engine.test-executor-thread][BatchEngineExportTaskExecutorImpl:90] Unable to update batch engine export task {"mvccVersion": 1, "uuid": "9b0d878f-46e7-5948-b17e-ffb109b5d179", "externalReferenceCode": "9b0d878f-46e7-5948-b17e-ffb109b5d179", "batchEngineExportTaskId": 10, "companyId": 20098, "userId": 49547, "createDate": "Sat Oct 08 02:38:34 GMT 2022", "modifiedDate": "Sat Oct 08 02:38:34 GMT 2022", "callbackURL": "", "className": "com.liferay.batch.engine.internal.test.BlogPosting", "contentType": "XLS", "endTime": "null", "errorMessage": "", "fieldNames": "articleBody,datePublished,headline,id", "executeStatus": "STARTED", "parameters": "{siteId=49543}", "processedItemsCount": 0, "startTime": "Sat Oct 08 02:38:34 GMT 2022", "taskItemDelegateName": "", "totalItemsCount": 0}
[beanshell] java.lang.NoClassDefFoundError: Could not initialize class org.apache.xmlbeans.XmlBeans
[beanshell] 	at org.openxmlformats.schemas.spreadsheetml.x2006.main.CTWorkbook$Factory.getTypeLoader(Unknown Source) ~[poi-ooxml-schemas-4.1.2.jar:4.1.2]
[beanshell] 	at org.openxmlformats.schemas.spreadsheetml.x2006.main.CTWorkbook$Factory.newInstance(Unknown Source) ~[poi-ooxml-schemas-4.1.2.jar:4.1.2]
```
[Testray](com.liferay.batch.engine.internal.test.BatchEngineImportTaskExecutorTest)

**Pull request closed without merging**
