### PR TITLE
LPS-138411

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-138411. 
Thanks for checking

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result again, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
Hi @jeffwu0724 whould you mind running these tests locally?

`FragmentEntryProcessorFreemarkerTest`, `FragmentEntryProcessorDropZoneTest`, `FragmentEntryProcessorEditableTest`
It presented this failure:
```
[exec] com.liferay.fragment.entry.processor.drop.zone.test.FragmentEntryProcessorDropZoneTest > classMethod FAILED
     [exec]     org.osgi.framework.BundleException: Could not resolve module: com.liferay.fragment.entry.processor.drop.zone.test [1464]
     [exec]       Unresolved requirement: Import-Package: javax.annotation.meta
     [exec]         at org.eclipse.osgi.container.Module.start(Module.java:444)
     [exec]         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
     [exec]         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:447)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.connector.FrameworkCommand.lambda$startBundle$37e16ea2$1(FrameworkCommand.java:46)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.connector.ArquillianConnectorThread.run(ArquillianConnectorThread.java:82)
     [exec] There were failing tests. See the report at: file:///opt/dev/projects/github/liferay-portal/modules/apps/fragment/fragment-entry-processor/fragment-entry-processor-drop-zone-test/build/reports/tests/testIntegration/index.html
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-26/test-portal-acceptance-pullrequest(master)/3189/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Pull request closed without merging**
