### PR TITLE
Remove deprecated for portal kernel part eight

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi,

I have removed the deprecated for
"setMailSession()" and its usage
"ListUtil.java"
"MapUtil.java"
"OSDetector.java"
"ResourceBundleLoader.java"
"ServerDetector.java"
"SubscriptionSender.java"
"WebKeys.java"
"DefaultWorkflowInstance.java"
"getURLEditWorkflowTask()"
"ClassResourceBundleLoader.java"
and eight deprecated classes
Thanks for checking. Also see https://github.com/jeffwu0724/liferay-portal/pull/47

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
ci:stop

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:stop

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by vicnate5** [comment]
I am having our new tester @catarineaguiar take a look at this one with my help

**Comment by vicnate5** [comment]
@jeffwu0724 No regressions found.

**Comment by jeffwu0724** [comment]
ci:test:sf

**Pull request closed without merging**
