### PR TITLE
LPS-172794

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
@Kvale1733 , could you please help me check the result? thanks!

**Comment by Kvale1733** [comment]
@jeffwu0724 Compile issues cases many tests to fail for several components due to filteredEntityField symbol not found

```
 [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/search-experiences/search-experiences-rest-test/src/testIntegration/java/com/liferay/search/experiences/rest/resource/v1_0/test/BaseSearchableAssetNameResourceTestCase.java:529: error: cannot find symbol
     [exec] 		return filteredEntityField;
     [exec] 		       ^
     [exec]   symbol:   variable filteredEntityField
     [exec]   location: class com.liferay.search.experiences.rest.resource.v1_0.test.BaseSearchableAssetNameResourceTestCase
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/search-experiences/search-experiences-rest-test/src/testIntegration/java/com/liferay/search/experiences/rest/resource/v1_0/test/BaseKeywordQueryContributorResourceTestCase.java:546: error: cannot find symbol
     [exec] 		return filteredEntityField;
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-31/test-portal-acceptance-pullrequest(master)/6717/modules-integration-mysql57-jdk8/1/8/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
thanks @Kvale1733 !

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Pull request closed without merging**
