### PR TITLE
LPS-142794

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-142794.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hi @catarineaguiar,

Could you help me check the PR result when it is done, please?
Thanks!

**Comment by catarineaguiar** [comment]
@jeffwu0724 possible regressions:

```
  [exec] com.liferay.search.experiences.internal.blueprint.search.request.enhancer.SXPBlueprintSearchRequestEnhancerImplTest > testMustBeClause FAILED
     [exec]     org.mockito.exceptions.base.MockitoException: 
     [exec]     Mockito cannot mock this class: interface com.liferay.portal.vulcan.dto.converter.DTOConverter.
     [exec] 
     [exec]     If you're not sure why you're getting this error, please report to the mailing list.
     [exec] 
     [exec] 
     [exec]     Java               : 1.8
     [exec]     JVM vendor name    : Oracle Corporation
     [exec]     JVM vendor version : 25.121-b13
     [exec]     JVM name           : Java HotSpot(TM) 64-Bit Server VM
     [exec]     JVM version        : 1.8.0_121-b13
     [exec]     JVM info           : mixed mode
     [exec]     OS name            : Linux
     [exec]     OS version         : 5.4.0-81-generic
     [exec] 
     [exec] 
     [exec]     You are seeing this disclaimer because Mockito is configured to create inlined mocks.
     [exec]     You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.
     [exec] 
     [exec]     Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [interface com.liferay.portal.vulcan.dto.converter.DTOConverter]
     [exec]         at com.liferay.search.experiences.internal.blueprint.search.request.enhancer.SXPBlueprintSearchRequestEnhancerImplTest._getComplexQueryPart(SXPBlueprintSearchRequestEnhancerImplTest.java:731)
     [exec]         at com.liferay.search.experiences.internal.blueprint.search.request.enhancer.SXPBlueprintSearchRequestEnhancerImplTest.testMustBeClause(SXPBlueprintSearchRequestEnhancerImplTest.java:394)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
```
[exec] com.liferay.sharepoint.soap.repository.connector.SharepointConnectionTest > testGetSharepointObjectsByQuery FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.sharepoint.soap.repository.connector.internal.util.RemoteExceptionSharepointExceptionMapper.map(RemoteExceptionSharepointExceptionMapper.java:39)
     [exec]         at com.liferay.sharepoint.soap.repository.connector.operation.GetSharepointObjectsByQueryOperation.execute(GetSharepointObjectsByQueryOperation.java:84)
     [exec]         at com.liferay.sharepoint.soap.repository.connector.operation.GetSharepointObjectsByFolderOperation.execute(GetSharepointObjectsByFolderOperation.java:46)
     [exec]         at com.liferay.sharepoint.soap.repository.connector.SharepointConnectionImpl.getSharepointObjects(SharepointConnectionImpl.java:227)
     [exec]         at com.liferay.sharepoint.soap.repository.connector.SharepointConnectionTest.deleteSharepointObjects(SharepointConnectionTest.java:738)
     [exec]         at com.liferay.sharepoint.soap.repository.connector.SharepointConnectionTest.setUp(SharepointConnectionTest.java:91)
     [exec]         at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
```
```
   [exec] Execution failed for task ':util:css-builder:writeMavenSettings'.
     [exec] > com/liferay/portal/kernel/util/TransformerFactoryUtil
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':util:css-builder:writeMavenSettings'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:208)
     [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:206)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:187)
     [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
     [exec] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-31/test-portal-acceptance-pullrequest(master)/4797/modules-unit-jdk8/0/4/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
