### PR TITLE
remove_deprecated_part_8_portal_impl

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
ci:stop

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
@catarineaguiar Please help me scan test results.

Thanks
Jeff

**Comment by catarineaguiar** [comment]
@vicnate5 will not have time to review this one today

**Comment by vicnate5** [comment]
@jeffwu0724 See https://github.com/jeffwu0724/liferay-portal/pull/64

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
