### PR TITLE
LPS-168749

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
@catarineaguiar Could you please help me check the test result when it is ready, please?

Thanks a lot!

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar, sorry to bother again. Could you please help me check the test result if you have any free time today, please?

Thanks!

**Comment by Kvale1733** [comment]
@jeffwu0724 A lot of tests faild on startup. Looks like an issue with SAML

```
2022-11-21 22:01:38.609 ERROR [main][DirectoryWatcher:1176] Unable to start bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.saml.web.jar
[beanshell] org.osgi.framework.BundleException: Could not resolve module: com.liferay.saml.web [738]
[beanshell]   Unresolved requirement: Import-Package: com.liferay.saml.opensaml.integration.field.expression.handler; version="1.1.0"
[beanshell]     -> Export-Package: com.liferay.saml.opensaml.integration.field.expression.handler; bundle-symbolic-name="com.liferay.saml.opensaml.integration"; bundle-version="5.3.42"; version="1.1.0"; uses:="com.liferay.portal.kernel.exception,com.liferay.portal.kernel.model,com.liferay.saml.opensaml.integration.processor.context,com.liferay.saml.persistence.model"
[beanshell]        com.liferay.saml.opensaml.integration [863]
[beanshell]          Unresolved requirement: Import-Package: org.apache.http.client.cache
[beanshell]   Unresolved requirement: Import-Package: com.liferay.saml.opensaml.integration.field.expression.handler.registry; version="1.0.0"
[beanshell]     -> Export-Package: com.liferay.saml.opensaml.integration.field.expression.handler.registry; bundle-symbolic-name="com.liferay.saml.opensaml.integration"; bundle-version="5.3.42"; version="1.0.1"; uses:="com.liferay.portal.kernel.model,com.liferay.saml.opensaml.integration.field.expression.handler,com.liferay.saml.opensaml.integration.processor.context,com.liferay.saml.persistence.model"
[beanshell] 
[beanshell] 	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundle(DirectoryWatcher.java:1159) [bundleFile:?]
```

[Example log](https://testray.liferay.com/reports/production/logs/2022-11/test-1-32/test-portal-acceptance-pullrequest(master)/7026/functional-tomcat90-mysql57-jdk8/0/7/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
Hi @Kvale1733, thanks man!

**Pull request closed without merging**
