### PR TITLE
move_upload_to_modues_test_4_6

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @Kvale1733 , could you please help me see what is wrong here when you have any free time, please?
Thanks!

**Comment by Kvale1733** [comment]
@jeffwu0724 

1 ) Compile issue in found in com.liferay.portal.upload.internal tests such as 
com.liferay.portal.upload.internal.LiferayFileItemTest
```
 [exec] > Task :apps:portal:portal-upload:classes
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal/portal-upload/src/test/java/com/liferay/portal/upload/internal/UploadServletRequestImplTest.java:24: error: package com.liferay.portal.uploader does not exist
     [exec] import com.liferay.portal.uploader.UploadServletRequestFactory;
     [exec]                                   ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal/portal-upload/src/test/java/com/liferay/portal/upload/internal/UploadServletRequestImplTest.java:123: error: cannot find symbol
     [exec] 	private UploadServletRequestFactory _uploadServletRequestFactory;
     [exec] 	        ^
     [exec]   symbol:   class UploadServletRequestFactory
     [exec]   location: class com.liferay.portal.upload.internal.UploadServletRequestImplTest
     [exec] 2 errors
     [exec] 
     [exec] > Task :apps:portal:portal-upload:compileTestJava FAILED
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-26/test-portal-acceptance-pullrequest(master)/8663/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

2)  com.liferay.portal.util.test.PortalImplTest
```
[exec] com.liferay.portal.util.test.PortalImplTest > testGetUploadPortletRequestWithValidHttpServletRequest FAILED
     [exec]     java.lang.ClassNotFoundException: com.liferay.portal.upload.UploadServletRequestImpl cannot be found by com.liferay.portal.util.test_1.0.0
     [exec]     	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:457)
     [exec]     	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:419)
     [exec]     	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:411)
     [exec]     	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:151)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-26/test-portal-acceptance-pullrequest(master)/8663/modules-integration-mysql57-jdk8/3/16/jenkins-console.txt.gz?authuser=0)

3) com.liferay.portal.remote.json.web.service.web.internal.JSONWebServiceServiceActionTest
```
 [exec] com.liferay.portal.remote.json.web.service.web.internal.JSONWebServiceServiceActionTest > testMultipartRequestFilesUpload FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.portal.remote.json.web.service.web.internal.JSONWebServiceServiceActionTest.testMultipartRequestFilesUpload(JSONWebServiceServiceActionTest.java:185)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-26/test-portal-acceptance-pullrequest(master)/8663/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

4) Semver issue
```
 [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.object.display.context                 MAJOR      1.0.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   interface  com.liferay.object.display.context.ObjectEntryDisplayContext
     [exec]     		-   method     isDefaultUser()
     [exec]     			-   access     abstract
     [exec]     			-   return     boolean
     [exec]     		+   method     isGuestUser()
     [exec]     			+   access     abstract
     [exec]     			+   return     boolean
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 62.0.0
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-26/test-portal-acceptance-pullrequest(master)/8663/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @zhangyan0701 , could you please help me see what is wrong here?
Thanks!

**Comment by zhangyan0701** [comment]
@jeffwu0724 

The com.liferay.portal.uploader.internal.LiferayFileItemTest failed with NPE error:
```
##
## com.liferay.portal.uploader.internal.LiferayFileItemTest > testGetContentTypeFromRealFile
##

	java.lang.NullPointerException
		at com.liferay.portal.kernel.test.util.DependenciesTestUtil.getDependencyAsFile(DependenciesTestUtil.java:32)
		at com.liferay.portal.uploader.internal.LiferayFileItemTest.testGetContentTypeFromRealFile(LiferayFileItemTest.java:150)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
... ...
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-04/test-1-31/test-portal-acceptance-pullrequest(master)/7807/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0

Other failures are not related.

**Pull request closed without merging**
