### PR TITLE
New use compile only for commons codec

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar , could you please help me check if there is any regression in this PR, please?
Thanks!

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Pull request closed without merging**
