### PR TITLE
LPS-147678

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi,

This is for https://issues.liferay.com/browse/LPS-147678
I have update update com.azure:azure-sdk-bom version to 1.0.4, which will use azure-identity 1.3.6, which will include json-smart 4.5.7.
Thanks for checking. Also see https://github.com/jeffwu0724/liferay-portal/pull/49

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by vicnate5** [comment]
@catarineaguiar Can you check this one next? If you cannot get to this one today, just let me know.

**Comment by vicnate5** [comment]
This analysis is pending testray import and might be delayed by short testray downtime.

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test

**Comment by vicnate5** [comment]
@jeffwu0724 No regressions found.

**Pull request closed without merging**
